<?php


/**
 * This class defines the structure of the 'web_page_access' table.
 *
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Thu Jul  4 22:07:57 2013
 *
 *
 * This map class is used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    lib.model.map
 */
class WebPageAccessTableMap extends TableMap {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'lib.model.map.WebPageAccessTableMap';

	/**
	 * Initialize the table attributes, columns and validators
	 * Relations are not initialized by this method since they are lazy loaded
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function initialize()
	{
	  // attributes
		$this->setName('web_page_access');
		$this->setPhpName('WebPageAccess');
		$this->setClassname('WebPageAccess');
		$this->setPackage('lib.model');
		$this->setUseIdGenerator(true);
		// columns
		$this->addPrimaryKey('ID', 'Id', 'INTEGER', true, null, null);
		$this->addForeignKey('WEB_SESSION_ID', 'WebSessionId', 'INTEGER', 'web_session', 'ID', false, null, null);
		$this->addForeignKey('WEB_PAGE_ID', 'WebPageId', 'INTEGER', 'web_page', 'ID', false, null, null);
		$this->addColumn('IP', 'Ip', 'VARCHAR', false, 15, null);
		$this->addColumn('USER_AGENT', 'UserAgent', 'VARCHAR', false, 255, null);
		$this->addColumn('QUERY', 'Query', 'CLOB', false, null, null);
		$this->addColumn('CREATED_AT', 'CreatedAt', 'TIMESTAMP', false, null, null);
		// validators
	} // initialize()

	/**
	 * Build the RelationMap objects for this table relationships
	 */
	public function buildRelations()
	{
    $this->addRelation('WebSession', 'WebSession', RelationMap::MANY_TO_ONE, array('web_session_id' => 'id', ), 'CASCADE', null);
    $this->addRelation('WebPage', 'WebPage', RelationMap::MANY_TO_ONE, array('web_page_id' => 'id', ), 'CASCADE', null);
	} // buildRelations()

	/**
	 * 
	 * Gets the list of behaviors registered for this table
	 * 
	 * @return array Associative array (name => parameters) of behaviors
	 */
	public function getBehaviors()
	{
		return array(
			'symfony' => array('form' => 'true', 'filter' => 'true', ),
			'symfony_behaviors' => array(),
			'symfony_timestampable' => array('create_column' => 'created_at', ),
		);
	} // getBehaviors()

} // WebPageAccessTableMap
