<?php

/**
 * Base class that represents a row from the 'campaign_contact' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * ven. 04 mai 2012 08:48:39 CEST
 *
 * @package    lib.model.om
 */
abstract class BaseCampaignContact extends BaseObject  implements Persistent {


	/**
	 * The Peer class.
	 * Instance provides a convenient way of calling static methods on a class
	 * that calling code may not be able to identify.
	 * @var        CampaignContactPeer
	 */
	protected static $peer;

	/**
	 * The value for the id field.
	 * @var        int
	 */
	protected $id;

	/**
	 * The value for the campaign_id field.
	 * @var        int
	 */
	protected $campaign_id;

	/**
	 * The value for the contact_id field.
	 * @var        int
	 */
	protected $contact_id;

	/**
	 * The value for the sent_at field.
	 * @var        string
	 */
	protected $sent_at;

	/**
	 * The value for the failed_sent_at field.
	 * @var        string
	 */
	protected $failed_sent_at;

	/**
	 * The value for the view_at field.
	 * @var        string
	 */
	protected $view_at;

	/**
	 * The value for the view_user_agent field.
	 * @var        string
	 */
	protected $view_user_agent;

	/**
	 * The value for the clicked_at field.
	 * @var        string
	 */
	protected $clicked_at;

	/**
	 * The value for the unsubscribed_at field.
	 * @var        string
	 */
	protected $unsubscribed_at;

	/**
	 * The value for the raison field.
	 * @var        string
	 */
	protected $raison;

	/**
	 * The value for the unsubscribed_lists field.
	 * @var        string
	 */
	protected $unsubscribed_lists;

	/**
	 * The value for the bounce_type field.
	 * Note: this column has a database default value of: 1
	 * @var        int
	 */
	protected $bounce_type;

	/**
	 * @var        Campaign
	 */
	protected $aCampaign;

	/**
	 * @var        Contact
	 */
	protected $aContact;

	/**
	 * @var        array CampaignContactBounce[] Collection to store aggregation of CampaignContactBounce objects.
	 */
	protected $collCampaignContactBounces;

	/**
	 * @var        Criteria The criteria used to select the current contents of collCampaignContactBounces.
	 */
	private $lastCampaignContactBounceCriteria = null;

	/**
	 * @var        array CampaignClick[] Collection to store aggregation of CampaignClick objects.
	 */
	protected $collCampaignClicks;

	/**
	 * @var        Criteria The criteria used to select the current contents of collCampaignClicks.
	 */
	private $lastCampaignClickCriteria = null;

	/**
	 * Flag to prevent endless save loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInSave = false;

	/**
	 * Flag to prevent endless validation loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInValidation = false;

	// symfony behavior
	
	const PEER = 'CampaignContactPeer';

	/**
	 * Applies default values to this object.
	 * This method should be called from the object's constructor (or
	 * equivalent initialization method).
	 * @see        __construct()
	 */
	public function applyDefaultValues()
	{
		$this->bounce_type = 1;
	}

	/**
	 * Initializes internal state of BaseCampaignContact object.
	 * @see        applyDefaults()
	 */
	public function __construct()
	{
		parent::__construct();
		$this->applyDefaultValues();
	}

	/**
	 * Get the [id] column value.
	 * 
	 * @return     int
	 */
	public function getId()
	{
		return $this->id;
	}

	/**
	 * Get the [campaign_id] column value.
	 * 
	 * @return     int
	 */
	public function getCampaignId()
	{
		return $this->campaign_id;
	}

	/**
	 * Get the [contact_id] column value.
	 * 
	 * @return     int
	 */
	public function getContactId()
	{
		return $this->contact_id;
	}

	/**
	 * Get the [optionally formatted] temporal [sent_at] column value.
	 * 
	 *
	 * @param      string $format The date/time format string (either date()-style or strftime()-style).
	 *							If format is NULL, then the raw DateTime object will be returned.
	 * @return     mixed Formatted date/time value as string or DateTime object (if format is NULL), NULL if column is NULL, and 0 if column value is 0000-00-00 00:00:00
	 * @throws     PropelException - if unable to parse/validate the date/time value.
	 */
	public function getSentAt($format = 'Y-m-d H:i:s')
	{
		if ($this->sent_at === null) {
			return null;
		}


		if ($this->sent_at === '0000-00-00 00:00:00') {
			// while technically this is not a default value of NULL,
			// this seems to be closest in meaning.
			return null;
		} else {
			try {
				$dt = new DateTime($this->sent_at);
			} catch (Exception $x) {
				throw new PropelException("Internally stored date/time/timestamp value could not be converted to DateTime: " . var_export($this->sent_at, true), $x);
			}
		}

		if ($format === null) {
			// Because propel.useDateTimeClass is TRUE, we return a DateTime object.
			return $dt;
		} elseif (strpos($format, '%') !== false) {
			return strftime($format, $dt->format('U'));
		} else {
			return $dt->format($format);
		}
	}

	/**
	 * Get the [optionally formatted] temporal [failed_sent_at] column value.
	 * 
	 *
	 * @param      string $format The date/time format string (either date()-style or strftime()-style).
	 *							If format is NULL, then the raw DateTime object will be returned.
	 * @return     mixed Formatted date/time value as string or DateTime object (if format is NULL), NULL if column is NULL, and 0 if column value is 0000-00-00 00:00:00
	 * @throws     PropelException - if unable to parse/validate the date/time value.
	 */
	public function getFailedSentAt($format = 'Y-m-d H:i:s')
	{
		if ($this->failed_sent_at === null) {
			return null;
		}


		if ($this->failed_sent_at === '0000-00-00 00:00:00') {
			// while technically this is not a default value of NULL,
			// this seems to be closest in meaning.
			return null;
		} else {
			try {
				$dt = new DateTime($this->failed_sent_at);
			} catch (Exception $x) {
				throw new PropelException("Internally stored date/time/timestamp value could not be converted to DateTime: " . var_export($this->failed_sent_at, true), $x);
			}
		}

		if ($format === null) {
			// Because propel.useDateTimeClass is TRUE, we return a DateTime object.
			return $dt;
		} elseif (strpos($format, '%') !== false) {
			return strftime($format, $dt->format('U'));
		} else {
			return $dt->format($format);
		}
	}

	/**
	 * Get the [optionally formatted] temporal [view_at] column value.
	 * 
	 *
	 * @param      string $format The date/time format string (either date()-style or strftime()-style).
	 *							If format is NULL, then the raw DateTime object will be returned.
	 * @return     mixed Formatted date/time value as string or DateTime object (if format is NULL), NULL if column is NULL, and 0 if column value is 0000-00-00 00:00:00
	 * @throws     PropelException - if unable to parse/validate the date/time value.
	 */
	public function getViewAt($format = 'Y-m-d H:i:s')
	{
		if ($this->view_at === null) {
			return null;
		}


		if ($this->view_at === '0000-00-00 00:00:00') {
			// while technically this is not a default value of NULL,
			// this seems to be closest in meaning.
			return null;
		} else {
			try {
				$dt = new DateTime($this->view_at);
			} catch (Exception $x) {
				throw new PropelException("Internally stored date/time/timestamp value could not be converted to DateTime: " . var_export($this->view_at, true), $x);
			}
		}

		if ($format === null) {
			// Because propel.useDateTimeClass is TRUE, we return a DateTime object.
			return $dt;
		} elseif (strpos($format, '%') !== false) {
			return strftime($format, $dt->format('U'));
		} else {
			return $dt->format($format);
		}
	}

	/**
	 * Get the [view_user_agent] column value.
	 * 
	 * @return     string
	 */
	public function getViewUserAgent()
	{
		return $this->view_user_agent;
	}

	/**
	 * Get the [optionally formatted] temporal [clicked_at] column value.
	 * 
	 *
	 * @param      string $format The date/time format string (either date()-style or strftime()-style).
	 *							If format is NULL, then the raw DateTime object will be returned.
	 * @return     mixed Formatted date/time value as string or DateTime object (if format is NULL), NULL if column is NULL, and 0 if column value is 0000-00-00 00:00:00
	 * @throws     PropelException - if unable to parse/validate the date/time value.
	 */
	public function getClickedAt($format = 'Y-m-d H:i:s')
	{
		if ($this->clicked_at === null) {
			return null;
		}


		if ($this->clicked_at === '0000-00-00 00:00:00') {
			// while technically this is not a default value of NULL,
			// this seems to be closest in meaning.
			return null;
		} else {
			try {
				$dt = new DateTime($this->clicked_at);
			} catch (Exception $x) {
				throw new PropelException("Internally stored date/time/timestamp value could not be converted to DateTime: " . var_export($this->clicked_at, true), $x);
			}
		}

		if ($format === null) {
			// Because propel.useDateTimeClass is TRUE, we return a DateTime object.
			return $dt;
		} elseif (strpos($format, '%') !== false) {
			return strftime($format, $dt->format('U'));
		} else {
			return $dt->format($format);
		}
	}

	/**
	 * Get the [optionally formatted] temporal [unsubscribed_at] column value.
	 * 
	 *
	 * @param      string $format The date/time format string (either date()-style or strftime()-style).
	 *							If format is NULL, then the raw DateTime object will be returned.
	 * @return     mixed Formatted date/time value as string or DateTime object (if format is NULL), NULL if column is NULL, and 0 if column value is 0000-00-00 00:00:00
	 * @throws     PropelException - if unable to parse/validate the date/time value.
	 */
	public function getUnsubscribedAt($format = 'Y-m-d H:i:s')
	{
		if ($this->unsubscribed_at === null) {
			return null;
		}


		if ($this->unsubscribed_at === '0000-00-00 00:00:00') {
			// while technically this is not a default value of NULL,
			// this seems to be closest in meaning.
			return null;
		} else {
			try {
				$dt = new DateTime($this->unsubscribed_at);
			} catch (Exception $x) {
				throw new PropelException("Internally stored date/time/timestamp value could not be converted to DateTime: " . var_export($this->unsubscribed_at, true), $x);
			}
		}

		if ($format === null) {
			// Because propel.useDateTimeClass is TRUE, we return a DateTime object.
			return $dt;
		} elseif (strpos($format, '%') !== false) {
			return strftime($format, $dt->format('U'));
		} else {
			return $dt->format($format);
		}
	}

	/**
	 * Get the [raison] column value.
	 * 
	 * @return     string
	 */
	public function getRaison()
	{
		return $this->raison;
	}

	/**
	 * Get the [unsubscribed_lists] column value.
	 * 
	 * @return     string
	 */
	public function getUnsubscribedLists()
	{
		return $this->unsubscribed_lists;
	}

	/**
	 * Get the [bounce_type] column value.
	 * 
	 * @return     int
	 */
	public function getBounceType()
	{
		return $this->bounce_type;
	}

	/**
	 * Set the value of [id] column.
	 * 
	 * @param      int $v new value
	 * @return     CampaignContact The current object (for fluent API support)
	 */
	public function setId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->id !== $v) {
			$this->id = $v;
			$this->modifiedColumns[] = CampaignContactPeer::ID;
		}

		return $this;
	} // setId()

	/**
	 * Set the value of [campaign_id] column.
	 * 
	 * @param      int $v new value
	 * @return     CampaignContact The current object (for fluent API support)
	 */
	public function setCampaignId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->campaign_id !== $v) {
			$this->campaign_id = $v;
			$this->modifiedColumns[] = CampaignContactPeer::CAMPAIGN_ID;
		}

		if ($this->aCampaign !== null && $this->aCampaign->getId() !== $v) {
			$this->aCampaign = null;
		}

		return $this;
	} // setCampaignId()

	/**
	 * Set the value of [contact_id] column.
	 * 
	 * @param      int $v new value
	 * @return     CampaignContact The current object (for fluent API support)
	 */
	public function setContactId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->contact_id !== $v) {
			$this->contact_id = $v;
			$this->modifiedColumns[] = CampaignContactPeer::CONTACT_ID;
		}

		if ($this->aContact !== null && $this->aContact->getId() !== $v) {
			$this->aContact = null;
		}

		return $this;
	} // setContactId()

	/**
	 * Sets the value of [sent_at] column to a normalized version of the date/time value specified.
	 * 
	 * @param      mixed $v string, integer (timestamp), or DateTime value.  Empty string will
	 *						be treated as NULL for temporal objects.
	 * @return     CampaignContact The current object (for fluent API support)
	 */
	public function setSentAt($v)
	{
		// we treat '' as NULL for temporal objects because DateTime('') == DateTime('now')
		// -- which is unexpected, to say the least.
		if ($v === null || $v === '') {
			$dt = null;
		} elseif ($v instanceof DateTime) {
			$dt = $v;
		} else {
			// some string/numeric value passed; we normalize that so that we can
			// validate it.
			try {
				if (is_numeric($v)) { // if it's a unix timestamp
					$dt = new DateTime('@'.$v, new DateTimeZone('UTC'));
					// We have to explicitly specify and then change the time zone because of a
					// DateTime bug: http://bugs.php.net/bug.php?id=43003
					$dt->setTimeZone(new DateTimeZone(date_default_timezone_get()));
				} else {
					$dt = new DateTime($v);
				}
			} catch (Exception $x) {
				throw new PropelException('Error parsing date/time value: ' . var_export($v, true), $x);
			}
		}

		if ( $this->sent_at !== null || $dt !== null ) {
			// (nested ifs are a little easier to read in this case)

			$currNorm = ($this->sent_at !== null && $tmpDt = new DateTime($this->sent_at)) ? $tmpDt->format('Y-m-d H:i:s') : null;
			$newNorm = ($dt !== null) ? $dt->format('Y-m-d H:i:s') : null;

			if ( ($currNorm !== $newNorm) // normalized values don't match 
					)
			{
				$this->sent_at = ($dt ? $dt->format('Y-m-d H:i:s') : null);
				$this->modifiedColumns[] = CampaignContactPeer::SENT_AT;
			}
		} // if either are not null

		return $this;
	} // setSentAt()

	/**
	 * Sets the value of [failed_sent_at] column to a normalized version of the date/time value specified.
	 * 
	 * @param      mixed $v string, integer (timestamp), or DateTime value.  Empty string will
	 *						be treated as NULL for temporal objects.
	 * @return     CampaignContact The current object (for fluent API support)
	 */
	public function setFailedSentAt($v)
	{
		// we treat '' as NULL for temporal objects because DateTime('') == DateTime('now')
		// -- which is unexpected, to say the least.
		if ($v === null || $v === '') {
			$dt = null;
		} elseif ($v instanceof DateTime) {
			$dt = $v;
		} else {
			// some string/numeric value passed; we normalize that so that we can
			// validate it.
			try {
				if (is_numeric($v)) { // if it's a unix timestamp
					$dt = new DateTime('@'.$v, new DateTimeZone('UTC'));
					// We have to explicitly specify and then change the time zone because of a
					// DateTime bug: http://bugs.php.net/bug.php?id=43003
					$dt->setTimeZone(new DateTimeZone(date_default_timezone_get()));
				} else {
					$dt = new DateTime($v);
				}
			} catch (Exception $x) {
				throw new PropelException('Error parsing date/time value: ' . var_export($v, true), $x);
			}
		}

		if ( $this->failed_sent_at !== null || $dt !== null ) {
			// (nested ifs are a little easier to read in this case)

			$currNorm = ($this->failed_sent_at !== null && $tmpDt = new DateTime($this->failed_sent_at)) ? $tmpDt->format('Y-m-d H:i:s') : null;
			$newNorm = ($dt !== null) ? $dt->format('Y-m-d H:i:s') : null;

			if ( ($currNorm !== $newNorm) // normalized values don't match 
					)
			{
				$this->failed_sent_at = ($dt ? $dt->format('Y-m-d H:i:s') : null);
				$this->modifiedColumns[] = CampaignContactPeer::FAILED_SENT_AT;
			}
		} // if either are not null

		return $this;
	} // setFailedSentAt()

	/**
	 * Sets the value of [view_at] column to a normalized version of the date/time value specified.
	 * 
	 * @param      mixed $v string, integer (timestamp), or DateTime value.  Empty string will
	 *						be treated as NULL for temporal objects.
	 * @return     CampaignContact The current object (for fluent API support)
	 */
	public function setViewAt($v)
	{
		// we treat '' as NULL for temporal objects because DateTime('') == DateTime('now')
		// -- which is unexpected, to say the least.
		if ($v === null || $v === '') {
			$dt = null;
		} elseif ($v instanceof DateTime) {
			$dt = $v;
		} else {
			// some string/numeric value passed; we normalize that so that we can
			// validate it.
			try {
				if (is_numeric($v)) { // if it's a unix timestamp
					$dt = new DateTime('@'.$v, new DateTimeZone('UTC'));
					// We have to explicitly specify and then change the time zone because of a
					// DateTime bug: http://bugs.php.net/bug.php?id=43003
					$dt->setTimeZone(new DateTimeZone(date_default_timezone_get()));
				} else {
					$dt = new DateTime($v);
				}
			} catch (Exception $x) {
				throw new PropelException('Error parsing date/time value: ' . var_export($v, true), $x);
			}
		}

		if ( $this->view_at !== null || $dt !== null ) {
			// (nested ifs are a little easier to read in this case)

			$currNorm = ($this->view_at !== null && $tmpDt = new DateTime($this->view_at)) ? $tmpDt->format('Y-m-d H:i:s') : null;
			$newNorm = ($dt !== null) ? $dt->format('Y-m-d H:i:s') : null;

			if ( ($currNorm !== $newNorm) // normalized values don't match 
					)
			{
				$this->view_at = ($dt ? $dt->format('Y-m-d H:i:s') : null);
				$this->modifiedColumns[] = CampaignContactPeer::VIEW_AT;
			}
		} // if either are not null

		return $this;
	} // setViewAt()

	/**
	 * Set the value of [view_user_agent] column.
	 * 
	 * @param      string $v new value
	 * @return     CampaignContact The current object (for fluent API support)
	 */
	public function setViewUserAgent($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->view_user_agent !== $v) {
			$this->view_user_agent = $v;
			$this->modifiedColumns[] = CampaignContactPeer::VIEW_USER_AGENT;
		}

		return $this;
	} // setViewUserAgent()

	/**
	 * Sets the value of [clicked_at] column to a normalized version of the date/time value specified.
	 * 
	 * @param      mixed $v string, integer (timestamp), or DateTime value.  Empty string will
	 *						be treated as NULL for temporal objects.
	 * @return     CampaignContact The current object (for fluent API support)
	 */
	public function setClickedAt($v)
	{
		// we treat '' as NULL for temporal objects because DateTime('') == DateTime('now')
		// -- which is unexpected, to say the least.
		if ($v === null || $v === '') {
			$dt = null;
		} elseif ($v instanceof DateTime) {
			$dt = $v;
		} else {
			// some string/numeric value passed; we normalize that so that we can
			// validate it.
			try {
				if (is_numeric($v)) { // if it's a unix timestamp
					$dt = new DateTime('@'.$v, new DateTimeZone('UTC'));
					// We have to explicitly specify and then change the time zone because of a
					// DateTime bug: http://bugs.php.net/bug.php?id=43003
					$dt->setTimeZone(new DateTimeZone(date_default_timezone_get()));
				} else {
					$dt = new DateTime($v);
				}
			} catch (Exception $x) {
				throw new PropelException('Error parsing date/time value: ' . var_export($v, true), $x);
			}
		}

		if ( $this->clicked_at !== null || $dt !== null ) {
			// (nested ifs are a little easier to read in this case)

			$currNorm = ($this->clicked_at !== null && $tmpDt = new DateTime($this->clicked_at)) ? $tmpDt->format('Y-m-d H:i:s') : null;
			$newNorm = ($dt !== null) ? $dt->format('Y-m-d H:i:s') : null;

			if ( ($currNorm !== $newNorm) // normalized values don't match 
					)
			{
				$this->clicked_at = ($dt ? $dt->format('Y-m-d H:i:s') : null);
				$this->modifiedColumns[] = CampaignContactPeer::CLICKED_AT;
			}
		} // if either are not null

		return $this;
	} // setClickedAt()

	/**
	 * Sets the value of [unsubscribed_at] column to a normalized version of the date/time value specified.
	 * 
	 * @param      mixed $v string, integer (timestamp), or DateTime value.  Empty string will
	 *						be treated as NULL for temporal objects.
	 * @return     CampaignContact The current object (for fluent API support)
	 */
	public function setUnsubscribedAt($v)
	{
		// we treat '' as NULL for temporal objects because DateTime('') == DateTime('now')
		// -- which is unexpected, to say the least.
		if ($v === null || $v === '') {
			$dt = null;
		} elseif ($v instanceof DateTime) {
			$dt = $v;
		} else {
			// some string/numeric value passed; we normalize that so that we can
			// validate it.
			try {
				if (is_numeric($v)) { // if it's a unix timestamp
					$dt = new DateTime('@'.$v, new DateTimeZone('UTC'));
					// We have to explicitly specify and then change the time zone because of a
					// DateTime bug: http://bugs.php.net/bug.php?id=43003
					$dt->setTimeZone(new DateTimeZone(date_default_timezone_get()));
				} else {
					$dt = new DateTime($v);
				}
			} catch (Exception $x) {
				throw new PropelException('Error parsing date/time value: ' . var_export($v, true), $x);
			}
		}

		if ( $this->unsubscribed_at !== null || $dt !== null ) {
			// (nested ifs are a little easier to read in this case)

			$currNorm = ($this->unsubscribed_at !== null && $tmpDt = new DateTime($this->unsubscribed_at)) ? $tmpDt->format('Y-m-d H:i:s') : null;
			$newNorm = ($dt !== null) ? $dt->format('Y-m-d H:i:s') : null;

			if ( ($currNorm !== $newNorm) // normalized values don't match 
					)
			{
				$this->unsubscribed_at = ($dt ? $dt->format('Y-m-d H:i:s') : null);
				$this->modifiedColumns[] = CampaignContactPeer::UNSUBSCRIBED_AT;
			}
		} // if either are not null

		return $this;
	} // setUnsubscribedAt()

	/**
	 * Set the value of [raison] column.
	 * 
	 * @param      string $v new value
	 * @return     CampaignContact The current object (for fluent API support)
	 */
	public function setRaison($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->raison !== $v) {
			$this->raison = $v;
			$this->modifiedColumns[] = CampaignContactPeer::RAISON;
		}

		return $this;
	} // setRaison()

	/**
	 * Set the value of [unsubscribed_lists] column.
	 * 
	 * @param      string $v new value
	 * @return     CampaignContact The current object (for fluent API support)
	 */
	public function setUnsubscribedLists($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->unsubscribed_lists !== $v) {
			$this->unsubscribed_lists = $v;
			$this->modifiedColumns[] = CampaignContactPeer::UNSUBSCRIBED_LISTS;
		}

		return $this;
	} // setUnsubscribedLists()

	/**
	 * Set the value of [bounce_type] column.
	 * 
	 * @param      int $v new value
	 * @return     CampaignContact The current object (for fluent API support)
	 */
	public function setBounceType($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->bounce_type !== $v || $this->isNew()) {
			$this->bounce_type = $v;
			$this->modifiedColumns[] = CampaignContactPeer::BOUNCE_TYPE;
		}

		return $this;
	} // setBounceType()

	/**
	 * Indicates whether the columns in this object are only set to default values.
	 *
	 * This method can be used in conjunction with isModified() to indicate whether an object is both
	 * modified _and_ has some values set which are non-default.
	 *
	 * @return     boolean Whether the columns in this object are only been set with default values.
	 */
	public function hasOnlyDefaultValues()
	{
			if ($this->bounce_type !== 1) {
				return false;
			}

		// otherwise, everything was equal, so return TRUE
		return true;
	} // hasOnlyDefaultValues()

	/**
	 * Hydrates (populates) the object variables with values from the database resultset.
	 *
	 * An offset (0-based "start column") is specified so that objects can be hydrated
	 * with a subset of the columns in the resultset rows.  This is needed, for example,
	 * for results of JOIN queries where the resultset row includes columns from two or
	 * more tables.
	 *
	 * @param      array $row The row returned by PDOStatement->fetch(PDO::FETCH_NUM)
	 * @param      int $startcol 0-based offset column which indicates which restultset column to start with.
	 * @param      boolean $rehydrate Whether this object is being re-hydrated from the database.
	 * @return     int next starting column
	 * @throws     PropelException  - Any caught Exception will be rewrapped as a PropelException.
	 */
	public function hydrate($row, $startcol = 0, $rehydrate = false)
	{
		try {

			$this->id = ($row[$startcol + 0] !== null) ? (int) $row[$startcol + 0] : null;
			$this->campaign_id = ($row[$startcol + 1] !== null) ? (int) $row[$startcol + 1] : null;
			$this->contact_id = ($row[$startcol + 2] !== null) ? (int) $row[$startcol + 2] : null;
			$this->sent_at = ($row[$startcol + 3] !== null) ? (string) $row[$startcol + 3] : null;
			$this->failed_sent_at = ($row[$startcol + 4] !== null) ? (string) $row[$startcol + 4] : null;
			$this->view_at = ($row[$startcol + 5] !== null) ? (string) $row[$startcol + 5] : null;
			$this->view_user_agent = ($row[$startcol + 6] !== null) ? (string) $row[$startcol + 6] : null;
			$this->clicked_at = ($row[$startcol + 7] !== null) ? (string) $row[$startcol + 7] : null;
			$this->unsubscribed_at = ($row[$startcol + 8] !== null) ? (string) $row[$startcol + 8] : null;
			$this->raison = ($row[$startcol + 9] !== null) ? (string) $row[$startcol + 9] : null;
			$this->unsubscribed_lists = ($row[$startcol + 10] !== null) ? (string) $row[$startcol + 10] : null;
			$this->bounce_type = ($row[$startcol + 11] !== null) ? (int) $row[$startcol + 11] : null;
			$this->resetModified();

			$this->setNew(false);

			if ($rehydrate) {
				$this->ensureConsistency();
			}

			// FIXME - using NUM_COLUMNS may be clearer.
			return $startcol + 12; // 12 = CampaignContactPeer::NUM_COLUMNS - CampaignContactPeer::NUM_LAZY_LOAD_COLUMNS).

		} catch (Exception $e) {
			throw new PropelException("Error populating CampaignContact object", $e);
		}
	}

	/**
	 * Checks and repairs the internal consistency of the object.
	 *
	 * This method is executed after an already-instantiated object is re-hydrated
	 * from the database.  It exists to check any foreign keys to make sure that
	 * the objects related to the current object are correct based on foreign key.
	 *
	 * You can override this method in the stub class, but you should always invoke
	 * the base method from the overridden method (i.e. parent::ensureConsistency()),
	 * in case your model changes.
	 *
	 * @throws     PropelException
	 */
	public function ensureConsistency()
	{

		if ($this->aCampaign !== null && $this->campaign_id !== $this->aCampaign->getId()) {
			$this->aCampaign = null;
		}
		if ($this->aContact !== null && $this->contact_id !== $this->aContact->getId()) {
			$this->aContact = null;
		}
	} // ensureConsistency

	/**
	 * Reloads this object from datastore based on primary key and (optionally) resets all associated objects.
	 *
	 * This will only work if the object has been saved and has a valid primary key set.
	 *
	 * @param      boolean $deep (optional) Whether to also de-associated any related objects.
	 * @param      PropelPDO $con (optional) The PropelPDO connection to use.
	 * @return     void
	 * @throws     PropelException - if this object is deleted, unsaved or doesn't have pk match in db
	 */
	public function reload($deep = false, PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("Cannot reload a deleted object.");
		}

		if ($this->isNew()) {
			throw new PropelException("Cannot reload an unsaved object.");
		}

		if ($con === null) {
			$con = Propel::getConnection(CampaignContactPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		// We don't need to alter the object instance pool; we're just modifying this instance
		// already in the pool.

		$stmt = CampaignContactPeer::doSelectStmt($this->buildPkeyCriteria(), $con);
		$row = $stmt->fetch(PDO::FETCH_NUM);
		$stmt->closeCursor();
		if (!$row) {
			throw new PropelException('Cannot find matching row in the database to reload object values.');
		}
		$this->hydrate($row, 0, true); // rehydrate

		if ($deep) {  // also de-associate any related objects?

			$this->aCampaign = null;
			$this->aContact = null;
			$this->collCampaignContactBounces = null;
			$this->lastCampaignContactBounceCriteria = null;

			$this->collCampaignClicks = null;
			$this->lastCampaignClickCriteria = null;

		} // if (deep)
	}

	/**
	 * Removes this object from datastore and sets delete attribute.
	 *
	 * @param      PropelPDO $con
	 * @return     void
	 * @throws     PropelException
	 * @see        BaseObject::setDeleted()
	 * @see        BaseObject::isDeleted()
	 */
	public function delete(PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("This object has already been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(CampaignContactPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		try {
			$ret = $this->preDelete($con);
			// symfony_behaviors behavior
			foreach (sfMixer::getCallables('BaseCampaignContact:delete:pre') as $callable)
			{
			  if (call_user_func($callable, $this, $con))
			  {
			    $con->commit();
			
			    return;
			  }
			}

			if ($ret) {
				CampaignContactPeer::doDelete($this, $con);
				$this->postDelete($con);
				// symfony_behaviors behavior
				foreach (sfMixer::getCallables('BaseCampaignContact:delete:post') as $callable)
				{
				  call_user_func($callable, $this, $con);
				}

				$this->setDeleted(true);
				$con->commit();
			} else {
				$con->commit();
			}
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Persists this object to the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All modified related objects will also be persisted in the doSave()
	 * method.  This method wraps all precipitate database operations in a
	 * single transaction.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        doSave()
	 */
	public function save(PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("You cannot save an object that has been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(CampaignContactPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		$isInsert = $this->isNew();
		try {
			$ret = $this->preSave($con);
			// symfony_behaviors behavior
			foreach (sfMixer::getCallables('BaseCampaignContact:save:pre') as $callable)
			{
			  if (is_integer($affectedRows = call_user_func($callable, $this, $con)))
			  {
			    $con->commit();
			
			    return $affectedRows;
			  }
			}

			if ($isInsert) {
				$ret = $ret && $this->preInsert($con);
			} else {
				$ret = $ret && $this->preUpdate($con);
			}
			if ($ret) {
				$affectedRows = $this->doSave($con);
				if ($isInsert) {
					$this->postInsert($con);
				} else {
					$this->postUpdate($con);
				}
				$this->postSave($con);
				// symfony_behaviors behavior
				foreach (sfMixer::getCallables('BaseCampaignContact:save:post') as $callable)
				{
				  call_user_func($callable, $this, $con, $affectedRows);
				}

				CampaignContactPeer::addInstanceToPool($this);
			} else {
				$affectedRows = 0;
			}
			$con->commit();
			return $affectedRows;
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Performs the work of inserting or updating the row in the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All related objects are also updated in this method.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        save()
	 */
	protected function doSave(PropelPDO $con)
	{
		$affectedRows = 0; // initialize var to track total num of affected rows
		if (!$this->alreadyInSave) {
			$this->alreadyInSave = true;

			// We call the save method on the following object(s) if they
			// were passed to this object by their coresponding set
			// method.  This object relates to these object(s) by a
			// foreign key reference.

			if ($this->aCampaign !== null) {
				if ($this->aCampaign->isModified() || $this->aCampaign->isNew()) {
					$affectedRows += $this->aCampaign->save($con);
				}
				$this->setCampaign($this->aCampaign);
			}

			if ($this->aContact !== null) {
				if ($this->aContact->isModified() || $this->aContact->isNew()) {
					$affectedRows += $this->aContact->save($con);
				}
				$this->setContact($this->aContact);
			}

			if ($this->isNew() ) {
				$this->modifiedColumns[] = CampaignContactPeer::ID;
			}

			// If this object has been modified, then save it to the database.
			if ($this->isModified()) {
				if ($this->isNew()) {
					$pk = CampaignContactPeer::doInsert($this, $con);
					$affectedRows += 1; // we are assuming that there is only 1 row per doInsert() which
										 // should always be true here (even though technically
										 // BasePeer::doInsert() can insert multiple rows).

					$this->setId($pk);  //[IMV] update autoincrement primary key

					$this->setNew(false);
				} else {
					$affectedRows += CampaignContactPeer::doUpdate($this, $con);
				}

				$this->resetModified(); // [HL] After being saved an object is no longer 'modified'
			}

			if ($this->collCampaignContactBounces !== null) {
				foreach ($this->collCampaignContactBounces as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			if ($this->collCampaignClicks !== null) {
				foreach ($this->collCampaignClicks as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			$this->alreadyInSave = false;

		}
		return $affectedRows;
	} // doSave()

	/**
	 * Array of ValidationFailed objects.
	 * @var        array ValidationFailed[]
	 */
	protected $validationFailures = array();

	/**
	 * Gets any ValidationFailed objects that resulted from last call to validate().
	 *
	 *
	 * @return     array ValidationFailed[]
	 * @see        validate()
	 */
	public function getValidationFailures()
	{
		return $this->validationFailures;
	}

	/**
	 * Validates the objects modified field values and all objects related to this table.
	 *
	 * If $columns is either a column name or an array of column names
	 * only those columns are validated.
	 *
	 * @param      mixed $columns Column name or an array of column names.
	 * @return     boolean Whether all columns pass validation.
	 * @see        doValidate()
	 * @see        getValidationFailures()
	 */
	public function validate($columns = null)
	{
		$res = $this->doValidate($columns);
		if ($res === true) {
			$this->validationFailures = array();
			return true;
		} else {
			$this->validationFailures = $res;
			return false;
		}
	}

	/**
	 * This function performs the validation work for complex object models.
	 *
	 * In addition to checking the current object, all related objects will
	 * also be validated.  If all pass then <code>true</code> is returned; otherwise
	 * an aggreagated array of ValidationFailed objects will be returned.
	 *
	 * @param      array $columns Array of column names to validate.
	 * @return     mixed <code>true</code> if all validations pass; array of <code>ValidationFailed</code> objets otherwise.
	 */
	protected function doValidate($columns = null)
	{
		if (!$this->alreadyInValidation) {
			$this->alreadyInValidation = true;
			$retval = null;

			$failureMap = array();


			// We call the validate method on the following object(s) if they
			// were passed to this object by their coresponding set
			// method.  This object relates to these object(s) by a
			// foreign key reference.

			if ($this->aCampaign !== null) {
				if (!$this->aCampaign->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aCampaign->getValidationFailures());
				}
			}

			if ($this->aContact !== null) {
				if (!$this->aContact->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aContact->getValidationFailures());
				}
			}


			if (($retval = CampaignContactPeer::doValidate($this, $columns)) !== true) {
				$failureMap = array_merge($failureMap, $retval);
			}


				if ($this->collCampaignContactBounces !== null) {
					foreach ($this->collCampaignContactBounces as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}

				if ($this->collCampaignClicks !== null) {
					foreach ($this->collCampaignClicks as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}


			$this->alreadyInValidation = false;
		}

		return (!empty($failureMap) ? $failureMap : true);
	}

	/**
	 * Retrieves a field from the object by name passed in as a string.
	 *
	 * @param      string $name name
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     mixed Value of field.
	 */
	public function getByName($name, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = CampaignContactPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		$field = $this->getByPosition($pos);
		return $field;
	}

	/**
	 * Retrieves a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @return     mixed Value of field at $pos
	 */
	public function getByPosition($pos)
	{
		switch($pos) {
			case 0:
				return $this->getId();
				break;
			case 1:
				return $this->getCampaignId();
				break;
			case 2:
				return $this->getContactId();
				break;
			case 3:
				return $this->getSentAt();
				break;
			case 4:
				return $this->getFailedSentAt();
				break;
			case 5:
				return $this->getViewAt();
				break;
			case 6:
				return $this->getViewUserAgent();
				break;
			case 7:
				return $this->getClickedAt();
				break;
			case 8:
				return $this->getUnsubscribedAt();
				break;
			case 9:
				return $this->getRaison();
				break;
			case 10:
				return $this->getUnsubscribedLists();
				break;
			case 11:
				return $this->getBounceType();
				break;
			default:
				return null;
				break;
		} // switch()
	}

	/**
	 * Exports the object as an array.
	 *
	 * You can specify the key type of the array by passing one of the class
	 * type constants.
	 *
	 * @param      string $keyType (optional) One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                        BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM. Defaults to BasePeer::TYPE_PHPNAME.
	 * @param      boolean $includeLazyLoadColumns (optional) Whether to include lazy loaded columns.  Defaults to TRUE.
	 * @return     an associative array containing the field names (as keys) and field values
	 */
	public function toArray($keyType = BasePeer::TYPE_PHPNAME, $includeLazyLoadColumns = true)
	{
		$keys = CampaignContactPeer::getFieldNames($keyType);
		$result = array(
			$keys[0] => $this->getId(),
			$keys[1] => $this->getCampaignId(),
			$keys[2] => $this->getContactId(),
			$keys[3] => $this->getSentAt(),
			$keys[4] => $this->getFailedSentAt(),
			$keys[5] => $this->getViewAt(),
			$keys[6] => $this->getViewUserAgent(),
			$keys[7] => $this->getClickedAt(),
			$keys[8] => $this->getUnsubscribedAt(),
			$keys[9] => $this->getRaison(),
			$keys[10] => $this->getUnsubscribedLists(),
			$keys[11] => $this->getBounceType(),
		);
		return $result;
	}

	/**
	 * Sets a field from the object by name passed in as a string.
	 *
	 * @param      string $name peer name
	 * @param      mixed $value field value
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     void
	 */
	public function setByName($name, $value, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = CampaignContactPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		return $this->setByPosition($pos, $value);
	}

	/**
	 * Sets a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @param      mixed $value field value
	 * @return     void
	 */
	public function setByPosition($pos, $value)
	{
		switch($pos) {
			case 0:
				$this->setId($value);
				break;
			case 1:
				$this->setCampaignId($value);
				break;
			case 2:
				$this->setContactId($value);
				break;
			case 3:
				$this->setSentAt($value);
				break;
			case 4:
				$this->setFailedSentAt($value);
				break;
			case 5:
				$this->setViewAt($value);
				break;
			case 6:
				$this->setViewUserAgent($value);
				break;
			case 7:
				$this->setClickedAt($value);
				break;
			case 8:
				$this->setUnsubscribedAt($value);
				break;
			case 9:
				$this->setRaison($value);
				break;
			case 10:
				$this->setUnsubscribedLists($value);
				break;
			case 11:
				$this->setBounceType($value);
				break;
		} // switch()
	}

	/**
	 * Populates the object using an array.
	 *
	 * This is particularly useful when populating an object from one of the
	 * request arrays (e.g. $_POST).  This method goes through the column
	 * names, checking to see whether a matching key exists in populated
	 * array. If so the setByName() method is called for that column.
	 *
	 * You can specify the key type of the array by additionally passing one
	 * of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME,
	 * BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM.
	 * The default key type is the column's phpname (e.g. 'AuthorId')
	 *
	 * @param      array  $arr     An array to populate the object from.
	 * @param      string $keyType The type of keys the array uses.
	 * @return     void
	 */
	public function fromArray($arr, $keyType = BasePeer::TYPE_PHPNAME)
	{
		$keys = CampaignContactPeer::getFieldNames($keyType);

		if (array_key_exists($keys[0], $arr)) $this->setId($arr[$keys[0]]);
		if (array_key_exists($keys[1], $arr)) $this->setCampaignId($arr[$keys[1]]);
		if (array_key_exists($keys[2], $arr)) $this->setContactId($arr[$keys[2]]);
		if (array_key_exists($keys[3], $arr)) $this->setSentAt($arr[$keys[3]]);
		if (array_key_exists($keys[4], $arr)) $this->setFailedSentAt($arr[$keys[4]]);
		if (array_key_exists($keys[5], $arr)) $this->setViewAt($arr[$keys[5]]);
		if (array_key_exists($keys[6], $arr)) $this->setViewUserAgent($arr[$keys[6]]);
		if (array_key_exists($keys[7], $arr)) $this->setClickedAt($arr[$keys[7]]);
		if (array_key_exists($keys[8], $arr)) $this->setUnsubscribedAt($arr[$keys[8]]);
		if (array_key_exists($keys[9], $arr)) $this->setRaison($arr[$keys[9]]);
		if (array_key_exists($keys[10], $arr)) $this->setUnsubscribedLists($arr[$keys[10]]);
		if (array_key_exists($keys[11], $arr)) $this->setBounceType($arr[$keys[11]]);
	}

	/**
	 * Build a Criteria object containing the values of all modified columns in this object.
	 *
	 * @return     Criteria The Criteria object containing all modified values.
	 */
	public function buildCriteria()
	{
		$criteria = new Criteria(CampaignContactPeer::DATABASE_NAME);

		if ($this->isColumnModified(CampaignContactPeer::ID)) $criteria->add(CampaignContactPeer::ID, $this->id);
		if ($this->isColumnModified(CampaignContactPeer::CAMPAIGN_ID)) $criteria->add(CampaignContactPeer::CAMPAIGN_ID, $this->campaign_id);
		if ($this->isColumnModified(CampaignContactPeer::CONTACT_ID)) $criteria->add(CampaignContactPeer::CONTACT_ID, $this->contact_id);
		if ($this->isColumnModified(CampaignContactPeer::SENT_AT)) $criteria->add(CampaignContactPeer::SENT_AT, $this->sent_at);
		if ($this->isColumnModified(CampaignContactPeer::FAILED_SENT_AT)) $criteria->add(CampaignContactPeer::FAILED_SENT_AT, $this->failed_sent_at);
		if ($this->isColumnModified(CampaignContactPeer::VIEW_AT)) $criteria->add(CampaignContactPeer::VIEW_AT, $this->view_at);
		if ($this->isColumnModified(CampaignContactPeer::VIEW_USER_AGENT)) $criteria->add(CampaignContactPeer::VIEW_USER_AGENT, $this->view_user_agent);
		if ($this->isColumnModified(CampaignContactPeer::CLICKED_AT)) $criteria->add(CampaignContactPeer::CLICKED_AT, $this->clicked_at);
		if ($this->isColumnModified(CampaignContactPeer::UNSUBSCRIBED_AT)) $criteria->add(CampaignContactPeer::UNSUBSCRIBED_AT, $this->unsubscribed_at);
		if ($this->isColumnModified(CampaignContactPeer::RAISON)) $criteria->add(CampaignContactPeer::RAISON, $this->raison);
		if ($this->isColumnModified(CampaignContactPeer::UNSUBSCRIBED_LISTS)) $criteria->add(CampaignContactPeer::UNSUBSCRIBED_LISTS, $this->unsubscribed_lists);
		if ($this->isColumnModified(CampaignContactPeer::BOUNCE_TYPE)) $criteria->add(CampaignContactPeer::BOUNCE_TYPE, $this->bounce_type);

		return $criteria;
	}

	/**
	 * Builds a Criteria object containing the primary key for this object.
	 *
	 * Unlike buildCriteria() this method includes the primary key values regardless
	 * of whether or not they have been modified.
	 *
	 * @return     Criteria The Criteria object containing value(s) for primary key(s).
	 */
	public function buildPkeyCriteria()
	{
		$criteria = new Criteria(CampaignContactPeer::DATABASE_NAME);

		$criteria->add(CampaignContactPeer::ID, $this->id);
		$criteria->add(CampaignContactPeer::CAMPAIGN_ID, $this->campaign_id);
		$criteria->add(CampaignContactPeer::CONTACT_ID, $this->contact_id);

		return $criteria;
	}

	/**
	 * Returns the composite primary key for this object.
	 * The array elements will be in same order as specified in XML.
	 * @return     array
	 */
	public function getPrimaryKey()
	{
		$pks = array();

		$pks[0] = $this->getId();

		$pks[1] = $this->getCampaignId();

		$pks[2] = $this->getContactId();

		return $pks;
	}

	/**
	 * Set the [composite] primary key.
	 *
	 * @param      array $keys The elements of the composite key (order must match the order in XML file).
	 * @return     void
	 */
	public function setPrimaryKey($keys)
	{

		$this->setId($keys[0]);

		$this->setCampaignId($keys[1]);

		$this->setContactId($keys[2]);

	}

	/**
	 * Sets contents of passed object to values from current object.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      object $copyObj An object of CampaignContact (or compatible) type.
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @throws     PropelException
	 */
	public function copyInto($copyObj, $deepCopy = false)
	{

		$copyObj->setCampaignId($this->campaign_id);

		$copyObj->setContactId($this->contact_id);

		$copyObj->setSentAt($this->sent_at);

		$copyObj->setFailedSentAt($this->failed_sent_at);

		$copyObj->setViewAt($this->view_at);

		$copyObj->setViewUserAgent($this->view_user_agent);

		$copyObj->setClickedAt($this->clicked_at);

		$copyObj->setUnsubscribedAt($this->unsubscribed_at);

		$copyObj->setRaison($this->raison);

		$copyObj->setUnsubscribedLists($this->unsubscribed_lists);

		$copyObj->setBounceType($this->bounce_type);


		if ($deepCopy) {
			// important: temporarily setNew(false) because this affects the behavior of
			// the getter/setter methods for fkey referrer objects.
			$copyObj->setNew(false);

			foreach ($this->getCampaignContactBounces() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addCampaignContactBounce($relObj->copy($deepCopy));
				}
			}

			foreach ($this->getCampaignClicks() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addCampaignClick($relObj->copy($deepCopy));
				}
			}

		} // if ($deepCopy)


		$copyObj->setNew(true);

		$copyObj->setId(NULL); // this is a auto-increment column, so set to default value

	}

	/**
	 * Makes a copy of this object that will be inserted as a new row in table when saved.
	 * It creates a new object filling in the simple attributes, but skipping any primary
	 * keys that are defined for the table.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @return     CampaignContact Clone of current object.
	 * @throws     PropelException
	 */
	public function copy($deepCopy = false)
	{
		// we use get_class(), because this might be a subclass
		$clazz = get_class($this);
		$copyObj = new $clazz();
		$this->copyInto($copyObj, $deepCopy);
		return $copyObj;
	}

	/**
	 * Returns a peer instance associated with this om.
	 *
	 * Since Peer classes are not to have any instance attributes, this method returns the
	 * same instance for all member of this class. The method could therefore
	 * be static, but this would prevent one from overriding the behavior.
	 *
	 * @return     CampaignContactPeer
	 */
	public function getPeer()
	{
		if (self::$peer === null) {
			self::$peer = new CampaignContactPeer();
		}
		return self::$peer;
	}

	/**
	 * Declares an association between this object and a Campaign object.
	 *
	 * @param      Campaign $v
	 * @return     CampaignContact The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setCampaign(Campaign $v = null)
	{
		if ($v === null) {
			$this->setCampaignId(NULL);
		} else {
			$this->setCampaignId($v->getId());
		}

		$this->aCampaign = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the Campaign object, it will not be re-added.
		if ($v !== null) {
			$v->addCampaignContact($this);
		}

		return $this;
	}


	/**
	 * Get the associated Campaign object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     Campaign The associated Campaign object.
	 * @throws     PropelException
	 */
	public function getCampaign(PropelPDO $con = null)
	{
		if ($this->aCampaign === null && ($this->campaign_id !== null)) {
			$this->aCampaign = CampaignPeer::retrieveByPk($this->campaign_id);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->aCampaign->addCampaignContacts($this);
			 */
		}
		return $this->aCampaign;
	}

	/**
	 * Declares an association between this object and a Contact object.
	 *
	 * @param      Contact $v
	 * @return     CampaignContact The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setContact(Contact $v = null)
	{
		if ($v === null) {
			$this->setContactId(NULL);
		} else {
			$this->setContactId($v->getId());
		}

		$this->aContact = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the Contact object, it will not be re-added.
		if ($v !== null) {
			$v->addCampaignContact($this);
		}

		return $this;
	}


	/**
	 * Get the associated Contact object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     Contact The associated Contact object.
	 * @throws     PropelException
	 */
	public function getContact(PropelPDO $con = null)
	{
		if ($this->aContact === null && ($this->contact_id !== null)) {
			$this->aContact = ContactPeer::retrieveByPk($this->contact_id);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->aContact->addCampaignContacts($this);
			 */
		}
		return $this->aContact;
	}

	/**
	 * Clears out the collCampaignContactBounces collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addCampaignContactBounces()
	 */
	public function clearCampaignContactBounces()
	{
		$this->collCampaignContactBounces = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collCampaignContactBounces collection (array).
	 *
	 * By default this just sets the collCampaignContactBounces collection to an empty array (like clearcollCampaignContactBounces());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initCampaignContactBounces()
	{
		$this->collCampaignContactBounces = array();
	}

	/**
	 * Gets an array of CampaignContactBounce objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this CampaignContact has previously been saved, it will retrieve
	 * related CampaignContactBounces from storage. If this CampaignContact is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array CampaignContactBounce[]
	 * @throws     PropelException
	 */
	public function getCampaignContactBounces($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(CampaignContactPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collCampaignContactBounces === null) {
			if ($this->isNew()) {
			   $this->collCampaignContactBounces = array();
			} else {

				$criteria->add(CampaignContactBouncePeer::CAMPAIGN_CONTACT_ID, $this->id);

				CampaignContactBouncePeer::addSelectColumns($criteria);
				$this->collCampaignContactBounces = CampaignContactBouncePeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(CampaignContactBouncePeer::CAMPAIGN_CONTACT_ID, $this->id);

				CampaignContactBouncePeer::addSelectColumns($criteria);
				if (!isset($this->lastCampaignContactBounceCriteria) || !$this->lastCampaignContactBounceCriteria->equals($criteria)) {
					$this->collCampaignContactBounces = CampaignContactBouncePeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastCampaignContactBounceCriteria = $criteria;
		return $this->collCampaignContactBounces;
	}

	/**
	 * Returns the number of related CampaignContactBounce objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related CampaignContactBounce objects.
	 * @throws     PropelException
	 */
	public function countCampaignContactBounces(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(CampaignContactPeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collCampaignContactBounces === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(CampaignContactBouncePeer::CAMPAIGN_CONTACT_ID, $this->id);

				$count = CampaignContactBouncePeer::doCount($criteria, false, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(CampaignContactBouncePeer::CAMPAIGN_CONTACT_ID, $this->id);

				if (!isset($this->lastCampaignContactBounceCriteria) || !$this->lastCampaignContactBounceCriteria->equals($criteria)) {
					$count = CampaignContactBouncePeer::doCount($criteria, false, $con);
				} else {
					$count = count($this->collCampaignContactBounces);
				}
			} else {
				$count = count($this->collCampaignContactBounces);
			}
		}
		return $count;
	}

	/**
	 * Method called to associate a CampaignContactBounce object to this object
	 * through the CampaignContactBounce foreign key attribute.
	 *
	 * @param      CampaignContactBounce $l CampaignContactBounce
	 * @return     void
	 * @throws     PropelException
	 */
	public function addCampaignContactBounce(CampaignContactBounce $l)
	{
		if ($this->collCampaignContactBounces === null) {
			$this->initCampaignContactBounces();
		}
		if (!in_array($l, $this->collCampaignContactBounces, true)) { // only add it if the **same** object is not already associated
			array_push($this->collCampaignContactBounces, $l);
			$l->setCampaignContact($this);
		}
	}

	/**
	 * Clears out the collCampaignClicks collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addCampaignClicks()
	 */
	public function clearCampaignClicks()
	{
		$this->collCampaignClicks = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collCampaignClicks collection (array).
	 *
	 * By default this just sets the collCampaignClicks collection to an empty array (like clearcollCampaignClicks());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initCampaignClicks()
	{
		$this->collCampaignClicks = array();
	}

	/**
	 * Gets an array of CampaignClick objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this CampaignContact has previously been saved, it will retrieve
	 * related CampaignClicks from storage. If this CampaignContact is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array CampaignClick[]
	 * @throws     PropelException
	 */
	public function getCampaignClicks($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(CampaignContactPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collCampaignClicks === null) {
			if ($this->isNew()) {
			   $this->collCampaignClicks = array();
			} else {

				$criteria->add(CampaignClickPeer::CAMPAIGN_CONTACT_ID, $this->id);

				CampaignClickPeer::addSelectColumns($criteria);
				$this->collCampaignClicks = CampaignClickPeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(CampaignClickPeer::CAMPAIGN_CONTACT_ID, $this->id);

				CampaignClickPeer::addSelectColumns($criteria);
				if (!isset($this->lastCampaignClickCriteria) || !$this->lastCampaignClickCriteria->equals($criteria)) {
					$this->collCampaignClicks = CampaignClickPeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastCampaignClickCriteria = $criteria;
		return $this->collCampaignClicks;
	}

	/**
	 * Returns the number of related CampaignClick objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related CampaignClick objects.
	 * @throws     PropelException
	 */
	public function countCampaignClicks(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(CampaignContactPeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collCampaignClicks === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(CampaignClickPeer::CAMPAIGN_CONTACT_ID, $this->id);

				$count = CampaignClickPeer::doCount($criteria, false, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(CampaignClickPeer::CAMPAIGN_CONTACT_ID, $this->id);

				if (!isset($this->lastCampaignClickCriteria) || !$this->lastCampaignClickCriteria->equals($criteria)) {
					$count = CampaignClickPeer::doCount($criteria, false, $con);
				} else {
					$count = count($this->collCampaignClicks);
				}
			} else {
				$count = count($this->collCampaignClicks);
			}
		}
		return $count;
	}

	/**
	 * Method called to associate a CampaignClick object to this object
	 * through the CampaignClick foreign key attribute.
	 *
	 * @param      CampaignClick $l CampaignClick
	 * @return     void
	 * @throws     PropelException
	 */
	public function addCampaignClick(CampaignClick $l)
	{
		if ($this->collCampaignClicks === null) {
			$this->initCampaignClicks();
		}
		if (!in_array($l, $this->collCampaignClicks, true)) { // only add it if the **same** object is not already associated
			array_push($this->collCampaignClicks, $l);
			$l->setCampaignContact($this);
		}
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this CampaignContact is new, it will return
	 * an empty collection; or if this CampaignContact has previously
	 * been saved, it will retrieve related CampaignClicks from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in CampaignContact.
	 */
	public function getCampaignClicksJoinCampaignLink($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(CampaignContactPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collCampaignClicks === null) {
			if ($this->isNew()) {
				$this->collCampaignClicks = array();
			} else {

				$criteria->add(CampaignClickPeer::CAMPAIGN_CONTACT_ID, $this->id);

				$this->collCampaignClicks = CampaignClickPeer::doSelectJoinCampaignLink($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(CampaignClickPeer::CAMPAIGN_CONTACT_ID, $this->id);

			if (!isset($this->lastCampaignClickCriteria) || !$this->lastCampaignClickCriteria->equals($criteria)) {
				$this->collCampaignClicks = CampaignClickPeer::doSelectJoinCampaignLink($criteria, $con, $join_behavior);
			}
		}
		$this->lastCampaignClickCriteria = $criteria;

		return $this->collCampaignClicks;
	}

	/**
	 * Resets all collections of referencing foreign keys.
	 *
	 * This method is a user-space workaround for PHP's inability to garbage collect objects
	 * with circular references.  This is currently necessary when using Propel in certain
	 * daemon or large-volumne/high-memory operations.
	 *
	 * @param      boolean $deep Whether to also clear the references on all associated objects.
	 */
	public function clearAllReferences($deep = false)
	{
		if ($deep) {
			if ($this->collCampaignContactBounces) {
				foreach ((array) $this->collCampaignContactBounces as $o) {
					$o->clearAllReferences($deep);
				}
			}
			if ($this->collCampaignClicks) {
				foreach ((array) $this->collCampaignClicks as $o) {
					$o->clearAllReferences($deep);
				}
			}
		} // if ($deep)

		$this->collCampaignContactBounces = null;
		$this->collCampaignClicks = null;
			$this->aCampaign = null;
			$this->aContact = null;
	}

	// symfony_behaviors behavior
	
	/**
	 * Calls methods defined via {@link sfMixer}.
	 */
	public function __call($method, $arguments)
	{
	  if (!$callable = sfMixer::getCallable('BaseCampaignContact:'.$method))
	  {
	    throw new sfException(sprintf('Call to undefined method BaseCampaignContact::%s', $method));
	  }
	
	  array_unshift($arguments, $this);
	
	  return call_user_func_array($callable, $arguments);
	}

} // BaseCampaignContact
