<?php

/**
 * Base class that represents a row from the 'campaign_contact_bounce' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * ven. 21 juin 2013 16:53:24 CEST
 *
 * @package    lib.model.om
 */
abstract class BaseCampaignContactBounce extends BaseObject  implements Persistent {


	/**
	 * The Peer class.
	 * Instance provides a convenient way of calling static methods on a class
	 * that calling code may not be able to identify.
	 * @var        CampaignContactBouncePeer
	 */
	protected static $peer;

	/**
	 * The value for the id field.
	 * @var        int
	 */
	protected $id;

	/**
	 * The value for the campaign_contact_id field.
	 * @var        int
	 */
	protected $campaign_contact_id;

	/**
	 * The value for the error_code field.
	 * @var        string
	 */
	protected $error_code;

	/**
	 * The value for the address field.
	 * @var        string
	 */
	protected $address;

	/**
	 * The value for the bounce_type field.
	 * @var        int
	 */
	protected $bounce_type;

	/**
	 * The value for the arrived_at field.
	 * @var        string
	 */
	protected $arrived_at;

	/**
	 * The value for the message field.
	 * @var        string
	 */
	protected $message;

	/**
	 * @var        CampaignContact
	 */
	protected $aCampaignContact;

	/**
	 * Flag to prevent endless save loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInSave = false;

	/**
	 * Flag to prevent endless validation loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInValidation = false;

	// symfony behavior
	
	const PEER = 'CampaignContactBouncePeer';

	/**
	 * Get the [id] column value.
	 * 
	 * @return     int
	 */
	public function getId()
	{
		return $this->id;
	}

	/**
	 * Get the [campaign_contact_id] column value.
	 * 
	 * @return     int
	 */
	public function getCampaignContactId()
	{
		return $this->campaign_contact_id;
	}

	/**
	 * Get the [error_code] column value.
	 * 
	 * @return     string
	 */
	public function getErrorCode()
	{
		return $this->error_code;
	}

	/**
	 * Get the [address] column value.
	 * 
	 * @return     string
	 */
	public function getAddress()
	{
		return $this->address;
	}

	/**
	 * Get the [bounce_type] column value.
	 * 
	 * @return     int
	 */
	public function getBounceType()
	{
		return $this->bounce_type;
	}

	/**
	 * Get the [optionally formatted] temporal [arrived_at] column value.
	 * 
	 *
	 * @param      string $format The date/time format string (either date()-style or strftime()-style).
	 *							If format is NULL, then the raw DateTime object will be returned.
	 * @return     mixed Formatted date/time value as string or DateTime object (if format is NULL), NULL if column is NULL, and 0 if column value is 0000-00-00 00:00:00
	 * @throws     PropelException - if unable to parse/validate the date/time value.
	 */
	public function getArrivedAt($format = 'Y-m-d H:i:s')
	{
		if ($this->arrived_at === null) {
			return null;
		}


		if ($this->arrived_at === '0000-00-00 00:00:00') {
			// while technically this is not a default value of NULL,
			// this seems to be closest in meaning.
			return null;
		} else {
			try {
				$dt = new DateTime($this->arrived_at);
			} catch (Exception $x) {
				throw new PropelException("Internally stored date/time/timestamp value could not be converted to DateTime: " . var_export($this->arrived_at, true), $x);
			}
		}

		if ($format === null) {
			// Because propel.useDateTimeClass is TRUE, we return a DateTime object.
			return $dt;
		} elseif (strpos($format, '%') !== false) {
			return strftime($format, $dt->format('U'));
		} else {
			return $dt->format($format);
		}
	}

	/**
	 * Get the [message] column value.
	 * 
	 * @return     string
	 */
	public function getMessage()
	{
		return $this->message;
	}

	/**
	 * Set the value of [id] column.
	 * 
	 * @param      int $v new value
	 * @return     CampaignContactBounce The current object (for fluent API support)
	 */
	public function setId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->id !== $v) {
			$this->id = $v;
			$this->modifiedColumns[] = CampaignContactBouncePeer::ID;
		}

		return $this;
	} // setId()

	/**
	 * Set the value of [campaign_contact_id] column.
	 * 
	 * @param      int $v new value
	 * @return     CampaignContactBounce The current object (for fluent API support)
	 */
	public function setCampaignContactId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->campaign_contact_id !== $v) {
			$this->campaign_contact_id = $v;
			$this->modifiedColumns[] = CampaignContactBouncePeer::CAMPAIGN_CONTACT_ID;
		}

		if ($this->aCampaignContact !== null && $this->aCampaignContact->getId() !== $v) {
			$this->aCampaignContact = null;
		}

		return $this;
	} // setCampaignContactId()

	/**
	 * Set the value of [error_code] column.
	 * 
	 * @param      string $v new value
	 * @return     CampaignContactBounce The current object (for fluent API support)
	 */
	public function setErrorCode($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->error_code !== $v) {
			$this->error_code = $v;
			$this->modifiedColumns[] = CampaignContactBouncePeer::ERROR_CODE;
		}

		return $this;
	} // setErrorCode()

	/**
	 * Set the value of [address] column.
	 * 
	 * @param      string $v new value
	 * @return     CampaignContactBounce The current object (for fluent API support)
	 */
	public function setAddress($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->address !== $v) {
			$this->address = $v;
			$this->modifiedColumns[] = CampaignContactBouncePeer::ADDRESS;
		}

		return $this;
	} // setAddress()

	/**
	 * Set the value of [bounce_type] column.
	 * 
	 * @param      int $v new value
	 * @return     CampaignContactBounce The current object (for fluent API support)
	 */
	public function setBounceType($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->bounce_type !== $v) {
			$this->bounce_type = $v;
			$this->modifiedColumns[] = CampaignContactBouncePeer::BOUNCE_TYPE;
		}

		return $this;
	} // setBounceType()

	/**
	 * Sets the value of [arrived_at] column to a normalized version of the date/time value specified.
	 * 
	 * @param      mixed $v string, integer (timestamp), or DateTime value.  Empty string will
	 *						be treated as NULL for temporal objects.
	 * @return     CampaignContactBounce The current object (for fluent API support)
	 */
	public function setArrivedAt($v)
	{
		// we treat '' as NULL for temporal objects because DateTime('') == DateTime('now')
		// -- which is unexpected, to say the least.
		if ($v === null || $v === '') {
			$dt = null;
		} elseif ($v instanceof DateTime) {
			$dt = $v;
		} else {
			// some string/numeric value passed; we normalize that so that we can
			// validate it.
			try {
				if (is_numeric($v)) { // if it's a unix timestamp
					$dt = new DateTime('@'.$v, new DateTimeZone('UTC'));
					// We have to explicitly specify and then change the time zone because of a
					// DateTime bug: http://bugs.php.net/bug.php?id=43003
					$dt->setTimeZone(new DateTimeZone(date_default_timezone_get()));
				} else {
					$dt = new DateTime($v);
				}
			} catch (Exception $x) {
				throw new PropelException('Error parsing date/time value: ' . var_export($v, true), $x);
			}
		}

		if ( $this->arrived_at !== null || $dt !== null ) {
			// (nested ifs are a little easier to read in this case)

			$currNorm = ($this->arrived_at !== null && $tmpDt = new DateTime($this->arrived_at)) ? $tmpDt->format('Y-m-d H:i:s') : null;
			$newNorm = ($dt !== null) ? $dt->format('Y-m-d H:i:s') : null;

			if ( ($currNorm !== $newNorm) // normalized values don't match 
					)
			{
				$this->arrived_at = ($dt ? $dt->format('Y-m-d H:i:s') : null);
				$this->modifiedColumns[] = CampaignContactBouncePeer::ARRIVED_AT;
			}
		} // if either are not null

		return $this;
	} // setArrivedAt()

	/**
	 * Set the value of [message] column.
	 * 
	 * @param      string $v new value
	 * @return     CampaignContactBounce The current object (for fluent API support)
	 */
	public function setMessage($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->message !== $v) {
			$this->message = $v;
			$this->modifiedColumns[] = CampaignContactBouncePeer::MESSAGE;
		}

		return $this;
	} // setMessage()

	/**
	 * Indicates whether the columns in this object are only set to default values.
	 *
	 * This method can be used in conjunction with isModified() to indicate whether an object is both
	 * modified _and_ has some values set which are non-default.
	 *
	 * @return     boolean Whether the columns in this object are only been set with default values.
	 */
	public function hasOnlyDefaultValues()
	{
		// otherwise, everything was equal, so return TRUE
		return true;
	} // hasOnlyDefaultValues()

	/**
	 * Hydrates (populates) the object variables with values from the database resultset.
	 *
	 * An offset (0-based "start column") is specified so that objects can be hydrated
	 * with a subset of the columns in the resultset rows.  This is needed, for example,
	 * for results of JOIN queries where the resultset row includes columns from two or
	 * more tables.
	 *
	 * @param      array $row The row returned by PDOStatement->fetch(PDO::FETCH_NUM)
	 * @param      int $startcol 0-based offset column which indicates which restultset column to start with.
	 * @param      boolean $rehydrate Whether this object is being re-hydrated from the database.
	 * @return     int next starting column
	 * @throws     PropelException  - Any caught Exception will be rewrapped as a PropelException.
	 */
	public function hydrate($row, $startcol = 0, $rehydrate = false)
	{
		try {

			$this->id = ($row[$startcol + 0] !== null) ? (int) $row[$startcol + 0] : null;
			$this->campaign_contact_id = ($row[$startcol + 1] !== null) ? (int) $row[$startcol + 1] : null;
			$this->error_code = ($row[$startcol + 2] !== null) ? (string) $row[$startcol + 2] : null;
			$this->address = ($row[$startcol + 3] !== null) ? (string) $row[$startcol + 3] : null;
			$this->bounce_type = ($row[$startcol + 4] !== null) ? (int) $row[$startcol + 4] : null;
			$this->arrived_at = ($row[$startcol + 5] !== null) ? (string) $row[$startcol + 5] : null;
			$this->message = ($row[$startcol + 6] !== null) ? (string) $row[$startcol + 6] : null;
			$this->resetModified();

			$this->setNew(false);

			if ($rehydrate) {
				$this->ensureConsistency();
			}

			// FIXME - using NUM_COLUMNS may be clearer.
			return $startcol + 7; // 7 = CampaignContactBouncePeer::NUM_COLUMNS - CampaignContactBouncePeer::NUM_LAZY_LOAD_COLUMNS).

		} catch (Exception $e) {
			throw new PropelException("Error populating CampaignContactBounce object", $e);
		}
	}

	/**
	 * Checks and repairs the internal consistency of the object.
	 *
	 * This method is executed after an already-instantiated object is re-hydrated
	 * from the database.  It exists to check any foreign keys to make sure that
	 * the objects related to the current object are correct based on foreign key.
	 *
	 * You can override this method in the stub class, but you should always invoke
	 * the base method from the overridden method (i.e. parent::ensureConsistency()),
	 * in case your model changes.
	 *
	 * @throws     PropelException
	 */
	public function ensureConsistency()
	{

		if ($this->aCampaignContact !== null && $this->campaign_contact_id !== $this->aCampaignContact->getId()) {
			$this->aCampaignContact = null;
		}
	} // ensureConsistency

	/**
	 * Reloads this object from datastore based on primary key and (optionally) resets all associated objects.
	 *
	 * This will only work if the object has been saved and has a valid primary key set.
	 *
	 * @param      boolean $deep (optional) Whether to also de-associated any related objects.
	 * @param      PropelPDO $con (optional) The PropelPDO connection to use.
	 * @return     void
	 * @throws     PropelException - if this object is deleted, unsaved or doesn't have pk match in db
	 */
	public function reload($deep = false, PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("Cannot reload a deleted object.");
		}

		if ($this->isNew()) {
			throw new PropelException("Cannot reload an unsaved object.");
		}

		if ($con === null) {
			$con = Propel::getConnection(CampaignContactBouncePeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		// We don't need to alter the object instance pool; we're just modifying this instance
		// already in the pool.

		$stmt = CampaignContactBouncePeer::doSelectStmt($this->buildPkeyCriteria(), $con);
		$row = $stmt->fetch(PDO::FETCH_NUM);
		$stmt->closeCursor();
		if (!$row) {
			throw new PropelException('Cannot find matching row in the database to reload object values.');
		}
		$this->hydrate($row, 0, true); // rehydrate

		if ($deep) {  // also de-associate any related objects?

			$this->aCampaignContact = null;
		} // if (deep)
	}

	/**
	 * Removes this object from datastore and sets delete attribute.
	 *
	 * @param      PropelPDO $con
	 * @return     void
	 * @throws     PropelException
	 * @see        BaseObject::setDeleted()
	 * @see        BaseObject::isDeleted()
	 */
	public function delete(PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("This object has already been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(CampaignContactBouncePeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		try {
			$ret = $this->preDelete($con);
			// symfony_behaviors behavior
			foreach (sfMixer::getCallables('BaseCampaignContactBounce:delete:pre') as $callable)
			{
			  if (call_user_func($callable, $this, $con))
			  {
			    $con->commit();
			
			    return;
			  }
			}

			if ($ret) {
				CampaignContactBouncePeer::doDelete($this, $con);
				$this->postDelete($con);
				// symfony_behaviors behavior
				foreach (sfMixer::getCallables('BaseCampaignContactBounce:delete:post') as $callable)
				{
				  call_user_func($callable, $this, $con);
				}

				$this->setDeleted(true);
				$con->commit();
			} else {
				$con->commit();
			}
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Persists this object to the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All modified related objects will also be persisted in the doSave()
	 * method.  This method wraps all precipitate database operations in a
	 * single transaction.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        doSave()
	 */
	public function save(PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("You cannot save an object that has been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(CampaignContactBouncePeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		$isInsert = $this->isNew();
		try {
			$ret = $this->preSave($con);
			// symfony_behaviors behavior
			foreach (sfMixer::getCallables('BaseCampaignContactBounce:save:pre') as $callable)
			{
			  if (is_integer($affectedRows = call_user_func($callable, $this, $con)))
			  {
			    $con->commit();
			
			    return $affectedRows;
			  }
			}

			if ($isInsert) {
				$ret = $ret && $this->preInsert($con);
			} else {
				$ret = $ret && $this->preUpdate($con);
			}
			if ($ret) {
				$affectedRows = $this->doSave($con);
				if ($isInsert) {
					$this->postInsert($con);
				} else {
					$this->postUpdate($con);
				}
				$this->postSave($con);
				// symfony_behaviors behavior
				foreach (sfMixer::getCallables('BaseCampaignContactBounce:save:post') as $callable)
				{
				  call_user_func($callable, $this, $con, $affectedRows);
				}

				CampaignContactBouncePeer::addInstanceToPool($this);
			} else {
				$affectedRows = 0;
			}
			$con->commit();
			return $affectedRows;
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Performs the work of inserting or updating the row in the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All related objects are also updated in this method.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        save()
	 */
	protected function doSave(PropelPDO $con)
	{
		$affectedRows = 0; // initialize var to track total num of affected rows
		if (!$this->alreadyInSave) {
			$this->alreadyInSave = true;

			// We call the save method on the following object(s) if they
			// were passed to this object by their coresponding set
			// method.  This object relates to these object(s) by a
			// foreign key reference.

			if ($this->aCampaignContact !== null) {
				if ($this->aCampaignContact->isModified() || $this->aCampaignContact->isNew()) {
					$affectedRows += $this->aCampaignContact->save($con);
				}
				$this->setCampaignContact($this->aCampaignContact);
			}

			if ($this->isNew() ) {
				$this->modifiedColumns[] = CampaignContactBouncePeer::ID;
			}

			// If this object has been modified, then save it to the database.
			if ($this->isModified()) {
				if ($this->isNew()) {
					$pk = CampaignContactBouncePeer::doInsert($this, $con);
					$affectedRows += 1; // we are assuming that there is only 1 row per doInsert() which
										 // should always be true here (even though technically
										 // BasePeer::doInsert() can insert multiple rows).

					$this->setId($pk);  //[IMV] update autoincrement primary key

					$this->setNew(false);
				} else {
					$affectedRows += CampaignContactBouncePeer::doUpdate($this, $con);
				}

				$this->resetModified(); // [HL] After being saved an object is no longer 'modified'
			}

			$this->alreadyInSave = false;

		}
		return $affectedRows;
	} // doSave()

	/**
	 * Array of ValidationFailed objects.
	 * @var        array ValidationFailed[]
	 */
	protected $validationFailures = array();

	/**
	 * Gets any ValidationFailed objects that resulted from last call to validate().
	 *
	 *
	 * @return     array ValidationFailed[]
	 * @see        validate()
	 */
	public function getValidationFailures()
	{
		return $this->validationFailures;
	}

	/**
	 * Validates the objects modified field values and all objects related to this table.
	 *
	 * If $columns is either a column name or an array of column names
	 * only those columns are validated.
	 *
	 * @param      mixed $columns Column name or an array of column names.
	 * @return     boolean Whether all columns pass validation.
	 * @see        doValidate()
	 * @see        getValidationFailures()
	 */
	public function validate($columns = null)
	{
		$res = $this->doValidate($columns);
		if ($res === true) {
			$this->validationFailures = array();
			return true;
		} else {
			$this->validationFailures = $res;
			return false;
		}
	}

	/**
	 * This function performs the validation work for complex object models.
	 *
	 * In addition to checking the current object, all related objects will
	 * also be validated.  If all pass then <code>true</code> is returned; otherwise
	 * an aggreagated array of ValidationFailed objects will be returned.
	 *
	 * @param      array $columns Array of column names to validate.
	 * @return     mixed <code>true</code> if all validations pass; array of <code>ValidationFailed</code> objets otherwise.
	 */
	protected function doValidate($columns = null)
	{
		if (!$this->alreadyInValidation) {
			$this->alreadyInValidation = true;
			$retval = null;

			$failureMap = array();


			// We call the validate method on the following object(s) if they
			// were passed to this object by their coresponding set
			// method.  This object relates to these object(s) by a
			// foreign key reference.

			if ($this->aCampaignContact !== null) {
				if (!$this->aCampaignContact->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aCampaignContact->getValidationFailures());
				}
			}


			if (($retval = CampaignContactBouncePeer::doValidate($this, $columns)) !== true) {
				$failureMap = array_merge($failureMap, $retval);
			}



			$this->alreadyInValidation = false;
		}

		return (!empty($failureMap) ? $failureMap : true);
	}

	/**
	 * Retrieves a field from the object by name passed in as a string.
	 *
	 * @param      string $name name
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     mixed Value of field.
	 */
	public function getByName($name, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = CampaignContactBouncePeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		$field = $this->getByPosition($pos);
		return $field;
	}

	/**
	 * Retrieves a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @return     mixed Value of field at $pos
	 */
	public function getByPosition($pos)
	{
		switch($pos) {
			case 0:
				return $this->getId();
				break;
			case 1:
				return $this->getCampaignContactId();
				break;
			case 2:
				return $this->getErrorCode();
				break;
			case 3:
				return $this->getAddress();
				break;
			case 4:
				return $this->getBounceType();
				break;
			case 5:
				return $this->getArrivedAt();
				break;
			case 6:
				return $this->getMessage();
				break;
			default:
				return null;
				break;
		} // switch()
	}

	/**
	 * Exports the object as an array.
	 *
	 * You can specify the key type of the array by passing one of the class
	 * type constants.
	 *
	 * @param      string $keyType (optional) One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                        BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM. Defaults to BasePeer::TYPE_PHPNAME.
	 * @param      boolean $includeLazyLoadColumns (optional) Whether to include lazy loaded columns.  Defaults to TRUE.
	 * @return     an associative array containing the field names (as keys) and field values
	 */
	public function toArray($keyType = BasePeer::TYPE_PHPNAME, $includeLazyLoadColumns = true)
	{
		$keys = CampaignContactBouncePeer::getFieldNames($keyType);
		$result = array(
			$keys[0] => $this->getId(),
			$keys[1] => $this->getCampaignContactId(),
			$keys[2] => $this->getErrorCode(),
			$keys[3] => $this->getAddress(),
			$keys[4] => $this->getBounceType(),
			$keys[5] => $this->getArrivedAt(),
			$keys[6] => $this->getMessage(),
		);
		return $result;
	}

	/**
	 * Sets a field from the object by name passed in as a string.
	 *
	 * @param      string $name peer name
	 * @param      mixed $value field value
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     void
	 */
	public function setByName($name, $value, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = CampaignContactBouncePeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		return $this->setByPosition($pos, $value);
	}

	/**
	 * Sets a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @param      mixed $value field value
	 * @return     void
	 */
	public function setByPosition($pos, $value)
	{
		switch($pos) {
			case 0:
				$this->setId($value);
				break;
			case 1:
				$this->setCampaignContactId($value);
				break;
			case 2:
				$this->setErrorCode($value);
				break;
			case 3:
				$this->setAddress($value);
				break;
			case 4:
				$this->setBounceType($value);
				break;
			case 5:
				$this->setArrivedAt($value);
				break;
			case 6:
				$this->setMessage($value);
				break;
		} // switch()
	}

	/**
	 * Populates the object using an array.
	 *
	 * This is particularly useful when populating an object from one of the
	 * request arrays (e.g. $_POST).  This method goes through the column
	 * names, checking to see whether a matching key exists in populated
	 * array. If so the setByName() method is called for that column.
	 *
	 * You can specify the key type of the array by additionally passing one
	 * of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME,
	 * BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM.
	 * The default key type is the column's phpname (e.g. 'AuthorId')
	 *
	 * @param      array  $arr     An array to populate the object from.
	 * @param      string $keyType The type of keys the array uses.
	 * @return     void
	 */
	public function fromArray($arr, $keyType = BasePeer::TYPE_PHPNAME)
	{
		$keys = CampaignContactBouncePeer::getFieldNames($keyType);

		if (array_key_exists($keys[0], $arr)) $this->setId($arr[$keys[0]]);
		if (array_key_exists($keys[1], $arr)) $this->setCampaignContactId($arr[$keys[1]]);
		if (array_key_exists($keys[2], $arr)) $this->setErrorCode($arr[$keys[2]]);
		if (array_key_exists($keys[3], $arr)) $this->setAddress($arr[$keys[3]]);
		if (array_key_exists($keys[4], $arr)) $this->setBounceType($arr[$keys[4]]);
		if (array_key_exists($keys[5], $arr)) $this->setArrivedAt($arr[$keys[5]]);
		if (array_key_exists($keys[6], $arr)) $this->setMessage($arr[$keys[6]]);
	}

	/**
	 * Build a Criteria object containing the values of all modified columns in this object.
	 *
	 * @return     Criteria The Criteria object containing all modified values.
	 */
	public function buildCriteria()
	{
		$criteria = new Criteria(CampaignContactBouncePeer::DATABASE_NAME);

		if ($this->isColumnModified(CampaignContactBouncePeer::ID)) $criteria->add(CampaignContactBouncePeer::ID, $this->id);
		if ($this->isColumnModified(CampaignContactBouncePeer::CAMPAIGN_CONTACT_ID)) $criteria->add(CampaignContactBouncePeer::CAMPAIGN_CONTACT_ID, $this->campaign_contact_id);
		if ($this->isColumnModified(CampaignContactBouncePeer::ERROR_CODE)) $criteria->add(CampaignContactBouncePeer::ERROR_CODE, $this->error_code);
		if ($this->isColumnModified(CampaignContactBouncePeer::ADDRESS)) $criteria->add(CampaignContactBouncePeer::ADDRESS, $this->address);
		if ($this->isColumnModified(CampaignContactBouncePeer::BOUNCE_TYPE)) $criteria->add(CampaignContactBouncePeer::BOUNCE_TYPE, $this->bounce_type);
		if ($this->isColumnModified(CampaignContactBouncePeer::ARRIVED_AT)) $criteria->add(CampaignContactBouncePeer::ARRIVED_AT, $this->arrived_at);
		if ($this->isColumnModified(CampaignContactBouncePeer::MESSAGE)) $criteria->add(CampaignContactBouncePeer::MESSAGE, $this->message);

		return $criteria;
	}

	/**
	 * Builds a Criteria object containing the primary key for this object.
	 *
	 * Unlike buildCriteria() this method includes the primary key values regardless
	 * of whether or not they have been modified.
	 *
	 * @return     Criteria The Criteria object containing value(s) for primary key(s).
	 */
	public function buildPkeyCriteria()
	{
		$criteria = new Criteria(CampaignContactBouncePeer::DATABASE_NAME);

		$criteria->add(CampaignContactBouncePeer::ID, $this->id);

		return $criteria;
	}

	/**
	 * Returns the primary key for this object (row).
	 * @return     int
	 */
	public function getPrimaryKey()
	{
		return $this->getId();
	}

	/**
	 * Generic method to set the primary key (id column).
	 *
	 * @param      int $key Primary key.
	 * @return     void
	 */
	public function setPrimaryKey($key)
	{
		$this->setId($key);
	}

	/**
	 * Sets contents of passed object to values from current object.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      object $copyObj An object of CampaignContactBounce (or compatible) type.
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @throws     PropelException
	 */
	public function copyInto($copyObj, $deepCopy = false)
	{

		$copyObj->setCampaignContactId($this->campaign_contact_id);

		$copyObj->setErrorCode($this->error_code);

		$copyObj->setAddress($this->address);

		$copyObj->setBounceType($this->bounce_type);

		$copyObj->setArrivedAt($this->arrived_at);

		$copyObj->setMessage($this->message);


		$copyObj->setNew(true);

		$copyObj->setId(NULL); // this is a auto-increment column, so set to default value

	}

	/**
	 * Makes a copy of this object that will be inserted as a new row in table when saved.
	 * It creates a new object filling in the simple attributes, but skipping any primary
	 * keys that are defined for the table.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @return     CampaignContactBounce Clone of current object.
	 * @throws     PropelException
	 */
	public function copy($deepCopy = false)
	{
		// we use get_class(), because this might be a subclass
		$clazz = get_class($this);
		$copyObj = new $clazz();
		$this->copyInto($copyObj, $deepCopy);
		return $copyObj;
	}

	/**
	 * Returns a peer instance associated with this om.
	 *
	 * Since Peer classes are not to have any instance attributes, this method returns the
	 * same instance for all member of this class. The method could therefore
	 * be static, but this would prevent one from overriding the behavior.
	 *
	 * @return     CampaignContactBouncePeer
	 */
	public function getPeer()
	{
		if (self::$peer === null) {
			self::$peer = new CampaignContactBouncePeer();
		}
		return self::$peer;
	}

	/**
	 * Declares an association between this object and a CampaignContact object.
	 *
	 * @param      CampaignContact $v
	 * @return     CampaignContactBounce The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setCampaignContact(CampaignContact $v = null)
	{
		if ($v === null) {
			$this->setCampaignContactId(NULL);
		} else {
			$this->setCampaignContactId($v->getId());
		}

		$this->aCampaignContact = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the CampaignContact object, it will not be re-added.
		if ($v !== null) {
			$v->addCampaignContactBounce($this);
		}

		return $this;
	}


	/**
	 * Get the associated CampaignContact object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     CampaignContact The associated CampaignContact object.
	 * @throws     PropelException
	 */
	public function getCampaignContact(PropelPDO $con = null)
	{
		if ($this->aCampaignContact === null && ($this->campaign_contact_id !== null)) {
			$this->aCampaignContact = CampaignContactPeer::retrieveByPk($this->campaign_contact_id);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->aCampaignContact->addCampaignContactBounces($this);
			 */
		}
		return $this->aCampaignContact;
	}

	/**
	 * Resets all collections of referencing foreign keys.
	 *
	 * This method is a user-space workaround for PHP's inability to garbage collect objects
	 * with circular references.  This is currently necessary when using Propel in certain
	 * daemon or large-volumne/high-memory operations.
	 *
	 * @param      boolean $deep Whether to also clear the references on all associated objects.
	 */
	public function clearAllReferences($deep = false)
	{
		if ($deep) {
		} // if ($deep)

			$this->aCampaignContact = null;
	}

	// symfony_behaviors behavior
	
	/**
	 * Calls methods defined via {@link sfMixer}.
	 */
	public function __call($method, $arguments)
	{
	  if (!$callable = sfMixer::getCallable('BaseCampaignContactBounce:'.$method))
	  {
	    throw new sfException(sprintf('Call to undefined method BaseCampaignContactBounce::%s', $method));
	  }
	
	  array_unshift($arguments, $this);
	
	  return call_user_func_array($callable, $arguments);
	}

} // BaseCampaignContactBounce
