# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/11-App

# default values
#all:
af:
  website_url: 'http://local.af.catalyz-emailing2.fr'
  app_url: 'http://local.af.catalyz-emailing2.fr'
  options:
#    contact_group:  true
    email_validation: true
  mail:
    server: localhost
    port: 25
    from_name:      'Cci'
    from_email:     'newsletter-noreply@montauban.cci.fr'
    reply_email:    'newsletter-noreply@montauban.cci.fr'
    reply_server:   'server1.waterproof.fr'
    reply_login:    'newsletter-noreply@montauban.cci.fr'
    reply_password: 'xxx'
  tiny_mce:
#    options: 'plugins: "fullscreen,table,imagemanager,filemanager,paste,catalyz_link,media,advlink,style",theme:"advanced",theme_advanced_buttons1:"forecolor,fontsizeselect,bold,italic,|,link,unlink,|,bullist,|,insertimage,image,|,tablecontrols,code",theme_advanced_buttons2:"",theme_advanced_buttons3:"",theme_advanced_toolbar_location:"top",theme_advanced_toolbar_align:"left",theme_advanced_statusbar_location:"none",theme_advanced_path_location:"none",extended_valid_elements:"a[name|href|target|title|onclick|class|type],img[class|src|border|alt|title|hspace|vspace|width|height|align|onmouseover|onmouseout|name|style],hr[class|width|size|noshade],font[face|size|color|style],span[class|align|style],iframe[width|height|frameborder|scrolling|marginheight|marginwidth|src]",theme_advanced_blockformats:"p,h1,h2,h3,h4,h5",table_cell_styles:"",table_styles:"",advlink_styles:"",content_css:""'
    options: 'plugins: "fullscreen,table,imagemanager,filemanager,paste,catalyz_link,media,advlink,czCustomFields",theme:"advanced",theme_advanced_buttons1:"czCustomFields,formatselect,styleselect,forecolor,fontsizeselect,bold,italic,|,anchor,link,unlink,|,bullist,|,insertimage,image",theme_advanced_buttons2:"tablecontrols,code,pasteword",theme_advanced_buttons3:"",theme_advanced_toolbar_location:"top",theme_advanced_toolbar_align:"left",theme_advanced_statusbar_location:"none",theme_advanced_path_location:"none",extended_valid_elements:"a[name|href|target|title|onclick|class|type],img[class|src|border|alt|title|hspace|vspace|width|height|align|onmouseover|onmouseout|name|style],hr[class|width|size|noshade],font[face|size|color|style],span[class|align|style],iframe[width|height|frameborder|scrolling|marginheight|marginwidth|src]",theme_advanced_blockformats:"p,h1,h2,h3,h4,h5",table_cell_styles:"",table_styles:"",advlink_styles:"",content_css:"/comparexPlugin/images/campaign01/content.css"'

shordeaux:
#  website_url: 'http://www.montauban.cci.fr.local'
  app_url: 'http://local.emailing.kogys.com'
  options:
    contact_group:  true
    email_validation: true
  mail:
    server: localhost
    port: 25
    from_name:      'Cci'
    from_email:     'newsletter-noreply@montauban.cci.fr'
    reply_email:    'newsletter-noreply@montauban.cci.fr'
    reply_server:   'server1.waterproof.fr'
    reply_login:    'newsletter-noreply@montauban.cci.fr'
    reply_password: 'xxxx'
  tiny_mce:
    options: 'plugins: "fullscreen,table,imagemanager,filemanager,paste,catalyz_link,media,advlink",theme:"advanced",theme_advanced_buttons1:"styleselect,forecolor,fontsizeselect,bold,italic,|,link,unlink,|,bullist,|,insertimage,image,|,tablecontrols,code",theme_advanced_buttons2:"",theme_advanced_buttons3:"",theme_advanced_toolbar_location:"top",theme_advanced_toolbar_align:"left",theme_advanced_statusbar_location:"none",theme_advanced_path_location:"none",extended_valid_elements:"a[name|href|target|title|onclick|class|type],img[class|src|border|alt|title|hspace|vspace|width|height|align|onmouseover|onmouseout|name|style],hr[class|width|size|noshade],font[face|size|color|style],span[class|align|style],iframe[width|height|frameborder|scrolling|marginheight|marginwidth|src]",theme_advanced_blockformats:"p,h1,h2,h3,h4,h5",table_cell_styles:"",table_styles:"",advlink_styles:"",content_css:"/comparexPlugin/images/campaign01/content.css"'

all:
  app_url: 'http://local.af.catalyz-emailing2.fr'
  seed: 'c4t4lyz'
  fields:
    count: 10
  catalyz:
    tinymce_default_colors: '003366,333333,669933,006699,999999,fefefe,ff3333'
  options:
    contact_group: true
#  mail:
#    bcc:            'mailing@waterproof.fr'

  providers:
    additionnal: []
    disabled: []

  settings:
    default_limit: 15
    default_suffix: '- Catalyz Emailing'
#    display_campaign_parameters: false

  bounce:
    stop_count: 2

  divers:
    tracker_analytics_nofollow_domain: ['youtube','facebook','twitter']
  litmus:
    api_key: 'catalyz'
    api_username: 'catalyz'
    api_password: '3tu5ymog'
  landing:
    templates:
      - comparex
      - autodesk
