# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

login:
  url:   /login
  param: { module: user, action: login }

logout:
  url:   /logout
  param: { module: user, action: logout }


# default rules
homepage2:
  url:   /
  param: { module: homepage, action: routeToIndex }

homepage:
  url:   /home
  param: { module: homepage, action: index }

contacts:
  url:   /contacts
  param: { module: contacts, action: index }

campaigns:
  url:   /campaigns
  param: { module: campaigns, action: index }

campaigns_create:
  url:   /campaigns/create
  param: { module: campaigns, action: create }

campaigns_archived:
  url:   /campaigns
  param: { module: campaigns, action: archived }

settings:
  url:   /settings
  param: { module: settings, action: index }

campaign_statistics_summary:
  url:   /:slug/summary
  param: { module: statistics, action: index }


campaign_index:
  url:   /campaign/:slug
  param: { module: campaign, action: index }



# generic rules
# please, remove them by adding more specific rules
default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*
