# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

login:
  url:   /login
  param: { module: user, action: login }

#logout:
#  url:   /logout
#  param: { module: user, action: logout }

#SFGUARDPLUGIN
sf_guard_signin:
  url:   /login
  param: { module: sfGuardAuth, action: signin }

sf_guard_signout:
  url:   /logout
  param: { module: sfGuardAuth, action: signout }

sf_guard_password:
  url:   /request_password
  param: { module: sfGuardAuth, action: password }

#APPLICATION
catalyz-ajax-add-field:
  url: /catalyz/add-field/:ContentObjectClass/:FormType/:FieldName/:formId/:selected
  param: { module: wizard, action: ajaxAddForm }

campaign-wizard-preview-post:
  url:   /wizard/preview
  param: { module: wizard, action: preview }

campaign-wizard-preview:
  url:   /wizard/preview/:campaign
  param: { module: wizard, action: preview }

campaign-wizard-preview-text:
  url:   /wizard/preview-text/:campaign
  param: { module: wizard, action: previewText }

campaign-wizard-preview-text-post:
  url:   /wizard/preview-text
  param: { module: wizard, action: previewText }

catalyz-ajax-add-link-form:
  url: /wizard/add-field
  param: { module: wizard, action: ajaxAddLinkForm }

catalyz-ajax-create-thumbnail-path:
  url: /catalyz/create_thumbnail_path
  param: { module: wizard, action: createThumbnailPath }

# default rules
homepage:
  url:   /
  param: { module: homepage, action: index }

campaigns:
  url:   /campaigns
  param: { module: campaigns, action: index }

campaigns_do_create:
  url:   /campaigns/create
  param: { module: campaigns, action: create }

campaigns_handle_create:
  url:   /campaigns/handle/create
  param: { module: campaigns, action: handleCreate }

campaigns_create_from_zip:
  url:   /campaigns/create/zip
  param: { module: campaigns, action: createFromZip }

campaigns_create_from_url:
  url:   /campaigns/create/url
  param: { module: campaigns, action: createFromUrl }

campaigns_archived:
  url:   /campaigns/archived
  param: { module: campaigns, action: archived }

campaigns_templates:
  url:   /campaigns/templates
  param: { module: campaigns, action: templates }

campaigns_export:
  url:   /campaigns/export
  param: { module: campaigns, action: export }

template_do_archive:
  url:   /campaigns/template/archive/:slug
  param: { module: campaigns, action: templateArchive }

template_do_unarchive:
  url:   /campaigns/template/unarchive/:slug
  param: { module: campaigns, action: templateUnarchive }

#CAMPAIGN
unsubscribe:
  url:   /campaign/unsubscribe/key/:key
  param: { module: campaign, action: unsubscribe }

view-online:
  url:   /campaign/view/key/:key
  param: { module: campaign, action: view }

view-online-api:
  url:   /campaign/view/:id
  param: { module: campaign, action: viewFromApi }

campaign-print:
  url:   /campaign/print/key/:key
  param: { module: campaign, action: print }

spy:
  url:  /images/catalyz-emailing/key/:key
  param: { module: images, action: catalyzemailing }

spy_from_images:
  url:  /images/t/*
  param: { module: images, action: forward }

campaign_index:
  url:   /campaign/:slug
  param: { module: campaign, action: index }

campaign_do_archive:
  url:   /campaign/archive/:slug
  param: { module: campaign, action: archive }

campaign_do_unarchive:
  url:   /campaign/unarchive/:slug
  param: { module: campaign, action: unarchive }

campaign_do_delete:
  url:   /campaign/delete/:slug
  param: { module: campaign, action: delete }

campaign_do_copy:
  url:   /campaign/copy/:slug
  param: { module: campaign, action: copy }

campaign_handle_copy:
  url:   /campaign/handle/copy
  param: { module: campaign, action: handleCopy }

campaign_edit_content:
  url:   /campaign/edit/content/:slug
  param: { module: campaign, action: edit }

campaign_edit_analytics:
  url:   /campaign/edit/googleAnalytics/:slug
  param: { module: campaign, action: googleAnalytics }

campaign_edit_links:
  url:   /campaign/edit/links/:slug
  param: { module: campaign, action: links }

campaign_edit_targets:
  url:   /campaign/edit/targets/:slug
  param: { module: campaign, action: targets }

campaign-target-add:
  url: /campaign/edit/targets/:slug/add
  param:
    module: campaign
    action: targetAdd

campaign-target-add-provider:
  url: /campaign/edit/targets/:slug/add/:provider
  param:
    module: campaign
    action: targetAddProvider

campaign-target-add-provider-with-params:
  url: url: /campaign/edit/targets/:slug/add/:provider/*
  param:
    module: campaign
    action: targetAddProvider

campaign-target-cleanup-provider:
  url: /campaign/edit/targets/:slug/cleanup/:provider
  param:
    module: campaign
    action: targetCleanupProvider

campaign-target-cleanup:
  url: /campaign/edit/targets/:slug/cleanup
  param:
    module: campaign
    action: targetCleanup

campaign-contact-delete:
  url: /campaign/contactDelete/id/:id/campaignId/:campaignId
  param:
    module: campaign
    action: contactDelete

campaign-group-delete:
  url: /campaign/groupDelete/id/:id/campaignId/:campaignId
  param:
    module: campaign
    action: groupDelete

ajax:
  url: /contact/ajax
  param: { module: contacts, action: ajax }

campaign_do_resend:
  url:   /campaign/resend/:id
  param: { module: campaign, action: resend }

campaign_edit_return_errors:
  url:   /campaign/edit/returnErrors/:slug
  param: { module: campaign, action: returnErrors }

campaign_edit_scheduling:
  url:   /campaign/edit/scheduling/:slug
  param: { module: campaign, action: scheduling }

campaign_do_edit_header:
  url:   /campaign/edit/header/:slug
  param: { module: campaign, action: editHeader }

campaign_do_test:
  url:   /campaigns/test/:slug
  param: { module: campaign, action: test }

unsubscribeStep:
  url:   /campaigns/unsubscribeStep
  param: { module: campaign, action: unsubscribeStep }

campaign_do_create_relance:
  url:   /campaign/create/relance/:slug
  param: { module: campaign, action: createRelance }

#STATISTICS
campaign_statistics_summary:
  url:   /:slug/summary
  param: { module: statistics, action: index }

campaign_statistics_compare:
  url:   /:slug/compare
  param: { module: statistics, action: compare }

campaign_statistics_targets:
  url:   /:slug/targets
  param: { module: statistics, action: targets }

campaign_statistics_views:
  url:   /:slug/views
  param: { module: statistics, action: views }

campaign_statistics_show_links:
  url:   /:slug/showLinks
  param: { module: statistics, action: showLinks }

campaign_statistics_message:
  url:   /:slug/message
  param: { module: statistics, action: message }

campaign_statistics_show_browser:
  url:   /:slug/showBrowser
  param: { module: statistics, action: showBrowser }

campaign_statistics_display_iframe:
  url: /statistics/displayIframe/:slug
  param: { module: statistics, action: displayIframe }

campaign_statistics_display_message_iframe:
  url: /statistics/displayContentIframe/:slug
  param: { module: statistics, action: displayCampaignContentIframe }

campaign_statistics_show_clicks:
  url:   /statistics/showCLicks/:id
  param: { module: statistics, action: showClicks }

campaign_statistics_do_export_clicks:
  url:   /statistics/export/clicks
  param: { module: statistics, action: exportClicks }

campaign_statistics_do_export_targets:
  url:   /statistics/export/targets
  param: { module: statistics, action: exportTargets }

campaign_statistics_do_export_views:
  url:   /statistics/export/views
  param: { module: statistics, action: exportViews }

campaign_statistics_return_errors:
  url:   /:slug/returnErrors
  param: { module: statistics, action: returnErrors }

campaign_statistics_do_display_bounce_message:
  url:   /:slug/returnErrors/details/:id
  param: { module: statistics, action: displayBounceDetails }

campaign_statistics_do_export_bounces:
  url:   /:slug/returnErrors/export
  param: { module: statistics, action: exportBounces }

campaign_statistics_unsubscribe:
  url:   /:slug/unsubscribes
  param: { module: statistics, action: unsubscribe }

campaign_statistics_do_export_unsubscribe:
  url:   /:slug/unsubscribes/export
  param: { module: statistics, action: exportUnsubscribe }

campaign_statistics_landing_actions:
  url:   /:slug/landing-actions
  param: { module: statistics, action: landingActions }

campaign_statistics_do_export_landing:
  url:   /:slug/unsubscribes/export
  param: { module: statistics, action: exportLandingActions }

campaign_statistics_export:
  url:   /statistics/export
  param: { module: statistics, action: exportCampaignStatistics }



#CONTACTS
contacts:
  url:   /contacts
  param: { module: contacts, action: index }

contact_do_delete:
  url:   /contact/delete/:slug
  param: { module: contacts, action: delete }

contact_show:
  url:   /contact/show/:slug
  param: { module: contacts, action: show }

contact_edit:
  url:   /contact/edit/:slug
  param: { module: contacts, action: edit }

contact_reintroduce:
  url: /contact/reintroduce/slug/:slug
  param: { module: contacts, action: reintroduce }

contact_display_clicks:
  url: /contact/displayClicks/id/:id/campaignId/:campaignId
  param: { module: contacts, action: displayClicks }

contact_do_unsubscribe:
  url: /contact/unsubscribe/slug/:id/campaignId/:campaignId
  param: { module: contacts, action: unsubscribe }

contact_export:
  url:   /contact/export
  param: { module: contacts, action: export }

contact_do_ajax_sort_contact_list:
  url: /contact/ajax/sort
  param: { module: contacts, action: ajaxSortContactList }

contact_import:
  url:   /contact/import
  param: { module: contacts, action: import }

contact_do_export_sample:
  url:   /contact/export/sampleFile
  param: { module: contacts, action: exportSampleFile }
#GROUPS
groups:
  url:   /groups
  param: { module: groups, action: index }

group_edit:
  url:   /groups/edit/:slug
  param: { module: groups, action: edit }

group_view:
  url:   /groups/view/:slug
  param: { module: groups, action: view }

group_do_delete:
  url:   /groups/delete/:slug
  param: { module: groups, action: delete }

group_do_export:
  url:   /groups/export/:slug
  param: { module: groups, action: exportGroup }

group_do_archive:
  url:   /groups/archive/:slug
  param: { module: groups, action: archive }

group_do_unarchive:
  url:   /groups/unarchive/:slug
  param: { module: groups, action: unArchive }

#SETTINGS
settings:
  url:   /settings
  param: { module: settings, action: index }

settings_add_user:
  url:   /settings/user/add
  param: { module: settings, action: add }

settings_edit_user:
  url:   /settings/user/edit/:id
  param: { module: settings, action: edit }

settings_do_delete_user:
  url:   /settings/user/delete/:id
  param: { module: settings, action: delete }

settings_contact_list:
  url:   /settings/contactList
  param: { module: settings, action: contactList }

settings_custom_fields:
  url:   /settings/customFields
  param: { module: settings, action: customFields }

settings_unsubscribe:
  url:   /settings/unsubscribe
  param: { module: settings, action: unsubscribe }

settings_change_list_limit:
  url:   /settings/contactListLimit
  param: { module: settings, action: changeContactListLimit }

landing:
  url:   /landing
  param: { module: landing, action: index }

landing_add:
  url:   /landing/add
  param: { module: landing, action: add }

landing_edit:
  url:   /landing/edit/:id
  param: { module: landing, action: edit }

landing_update:
  url:   /landing/update
  param: { module: landing, action: update }

landing_delete:
  url:   /landing/delete/:id
  param: { module: landing, action: delete }

landing_duplicate:
  url:   /landing/duplicate/:id
  param: { module: landing, action: duplicate }

landing_show:
  url:   /page/:slug
  param: { module: landing, action: show }

landing_action:
  url:   /landing/action/:slug/:type
  param: { module: landing, action: action }

# -- Tracking
tracking_agent:
  url:   /t.js
  param: { module: tracking, action: agent }

tracking:
  url:   /tracking
  param: { module: tracking, action: index }

tracking_configuration:
  url:   /settings/tracking
  param: { module: tracking, action: settings }


# generic rules
# please, remove them by adding more specific rules
default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*
