# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

login:
  url:   /login
  param: { module: user, action: login }

#logout:
#  url:   /logout
#  param: { module: user, action: logout }

#SFGUARDPLUGIN
sf_guard_signin:
  url:   /login
  param: { module: sfGuardAuth, action: signin }

sf_guard_signout:
  url:   /logout
  param: { module: sfGuardAuth, action: signout }

sf_guard_password:
  url:   /request_password
  param: { module: sfGuardAuth, action: password }


# default rules
homepage2:
  url:   /
  param: { module: homepage, action: routeToIndex }

homepage:
  url:   /home
  param: { module: homepage, action: index }

campaigns:
  url:   /campaigns
  param: { module: campaigns, action: index }

campaigns_do_create:
  url:   /campaigns/create
  param: { module: campaigns, action: create }

campaigns_handle_create:
  url:   /campaigns/handle/create
  param: { module: campaigns, action: handleCreate }

campaigns_archived:
  url:   /campaigns/archived
  param: { module: campaigns, action: archived }

campaign_statistics_summary:
  url:   /:slug/summary
  param: { module: statistics, action: index }

#SETTINGS
settings:
  url:   /settings
  param: { module: settings, action: index }

settings_change_list_limit:
  url:   /settings/contactListLimit
  param: { module: settings, action: changeContactListLimit }

#CAMPAIGN
campaign_index:
  url:   /campaign/:slug
  param: { module: campaign, action: index }

campaign_do_archive:
  url:   /campaign/archive/:slug
  param: { module: campaign, action: archive }

campaign_do_unarchive:
  url:   /campaign/unarchive/:slug
  param: { module: campaign, action: unarchive }

campaign_do_delete:
  url:   /campaign/delete/:slug
  param: { module: campaign, action: delete }

campaign_do_copy:
  url:   /campaign/copy/:slug
  param: { module: campaign, action: copy }

campaign_handle_copy:
  url:   /campaign/handle/copy
  param: { module: campaign, action: handleCopy }

campaign_do_edit:
  url:   /campaign/edit/:slug
  param: { module: campaign, action: edit }

campaign_do_resend:
  url:   /campaign/resend/:slug
  param:
    module: campaign
    action: resend

#CONTACTS
contacts:
  url:   /contacts
  param: { module: contacts, action: index }

contact_do_delete:
  url:   /contact/delete/:slug
  param: { module: contacts, action: delete }

contact_show:
  url:   /contact/show/:slug
  param: { module: contacts, action: show }

contact_edit:
  url:   /contact/edit/:slug
  param: { module: contacts, action: edit }

contact_reintroduce:
  url: /contact/reintroduce/slug/:slug
  param:
    module: contacts
    action: reintroduce

contact_display_clicks:
  url: /contact/displayClicks/id/:id/campaignId/:campaignId
  param:
    module: contacts
    action: displayClicks

contact_do_unsubscribe:
  url: /contact/unsubscribe/slug/:id/campaignId/:campaignId
  param:
    module: contacts
    action: unsubscribe

# generic rules
# please, remove them by adding more specific rules
default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*
