# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

login:
  url:   /login
  param: { module: user, action: login }

#logout:
#  url:   /logout
#  param: { module: user, action: logout }

#SFGUARDPLUGIN
sf_guard_signin:
  url:   /login
  param: { module: sfGuardAuth, action: signin }

sf_guard_signout:
  url:   /logout
  param: { module: sfGuardAuth, action: signout }

sf_guard_password:
  url:   /request_password
  param: { module: sfGuardAuth, action: password }


# default rules
homepage2:
  url:   /
  param: { module: homepage, action: routeToIndex }

homepage:
  url:   /home
  param: { module: homepage, action: index }

campaigns:
  url:   /campaigns
  param: { module: campaigns, action: index }

campaigns_do_create:
  url:   /campaigns/create
  param: { module: campaigns, action: create }

campaigns_handle_create:
  url:   /campaigns/handle/create
  param: { module: campaigns, action: handleCreate }

campaigns_archived:
  url:   /campaigns/archived
  param: { module: campaigns, action: archived }

campaigns_templates:
  url:   /campaigns/templates
  param: { module: campaigns, action: templates }

template_do_archive:
  url:   /campaigns/template/archive/:slug
  param: { module: campaigns, action: templateArchive }

template_do_unarchive:
  url:   /campaigns/template/unarchive/:slug
  param: { module: campaigns, action: templateUnarchive }

#CAMPAIGN
unsubscribe:
  url:   /campaign/unsubscribe/key/:key
  param: { module: campaign, action: unsubscribe }

view-online:
  url:   /campaign/view/key/:key
  param: { module: campaign, action: view }

view-online-api:
  url:   /campaign/view/:id
  param: { module: campaign, action: viewFromApi }

campaign-print:
  url:   /campaign/print/key/:key
  param: { module: campaign, action: print }

spy:
  url:  /images/catalyz-emailing/key/:key
  param: { module: images, action: catalyzemailing }

spy_from_images:
  url:  /images/t/*
  param: { module: images, action: forward }

campaign_index:
  url:   /campaign/:slug
  param: { module: campaign, action: index }

campaign_do_archive:
  url:   /campaign/archive/:slug
  param: { module: campaign, action: archive }

campaign_do_unarchive:
  url:   /campaign/unarchive/:slug
  param: { module: campaign, action: unarchive }

campaign_do_delete:
  url:   /campaign/delete/:slug
  param: { module: campaign, action: delete }

campaign_do_copy:
  url:   /campaign/copy/:slug
  param: { module: campaign, action: copy }

campaign_handle_copy:
  url:   /campaign/handle/copy
  param: { module: campaign, action: handleCopy }

campaign_edit_content:
  url:   /campaign/edit/content/:slug
  param: { module: campaign, action: edit }

campaign_edit_analytics:
  url:   /campaign/edit/googleAnalytics/:slug
  param: { module: campaign, action: googleAnalytics }

campaign_edit_links:
  url:   /campaign/edit/links/:slug
  param: { module: campaign, action: links }

campaign_do_resend:
  url:   /campaign/resend/:id
  param: { module: campaign, action: resend }

campaign_edit_return_errors:
  url:   /campaign/edit/returnErrors/:slug
  param: { module: campaign, action: returnErrors }

campaign_edit_scheduling:
  url:   /campaign/edit/scheduling/:slug
  param: { module: campaign, action: scheduling }

campaign_do_edit_header:
  url:   /campaign/edit/header/:slug
  param: { module: campaign, action: editHeader }

#STATISTICS
campaign_statistics_summary:
  url:   /:slug/summary
  param: { module: statistics, action: index }

campaign_statistics_targets:
  url:   /:slug/targets
  param: { module: statistics, action: targets }

campaign_statistics_views:
  url:   /:slug/views
  param: { module: statistics, action: views }

campaign_statistics_show_links:
  url:   /:slug/showLinks
  param: { module: statistics, action: showLinks }

campaign_statistics_message:
  url:   /:slug/message
  param: { module: statistics, action: message }

campaign_statistics_show_browser:
  url:   /:slug/showBrowser
  param: { module: statistics, action: showBrowser }

campaign_statistics_display_iframe:
  url: /statistics/displayIframe/slug/:slug
  param: { module: statistics, action: displayIframe }

campaign_statistics_display_message_iframe:
  url: /statistics/displayContentIframe/slug/:slug
  param: { module: statistics, action: displayCampaignContentIframe }

campaign_statistics_show_clicks:
  url:   /statistics/showCLicks/:id
  param: { module: statistics, action: showClicks }

#CONTACTS
contacts:
  url:   /contacts
  param: { module: contacts, action: index }

contact_do_delete:
  url:   /contact/delete/:slug
  param: { module: contacts, action: delete }

contact_show:
  url:   /contact/show/:slug
  param: { module: contacts, action: show }

contact_edit:
  url:   /contact/edit/:slug
  param: { module: contacts, action: edit }

contact_reintroduce:
  url: /contact/reintroduce/slug/:slug
  param: { module: contacts, action: reintroduce }

contact_display_clicks:
  url: /contact/displayClicks/id/:id/campaignId/:campaignId
  param: { module: contacts, action: displayClicks }

contact_do_unsubscribe:
  url: /contact/unsubscribe/slug/:id/campaignId/:campaignId
  param: { module: contacts, action: unsubscribe }

contact_export:
  url:   /contact/export
  param: { module: contacts, action: export }

#GROUPS
groups:
  url:   /groups
  param: { module: groups, action: index }

group_edit:
  url:   /groups/edit/:slug
  param: { module: groups, action: edit }

group_view:
  url:   /groups/view/:slug
  param: { module: groups, action: view }

group_do_delete:
  url:   /groups/delete/:slug
  param: { module: groups, action: delete }

group_do_export:
  url:   /groups/export/:slug
  param: { module: groups, action: exportGroup }

group_do_archive:
  url:   /groups/archive/:slug
  param: { module: groups, action: archive }

group_do_unarchive:
  url:   /groups/unarchive/:slug
  param: { module: groups, action: unArchive }

#SETTINGS
settings:
  url:   /settings
  param: { module: settings, action: index }

settings_add_user:
  url:   /settings/user/add
  param: { module: settings, action: add }

settings_edit_user:
  url:   /settings/user/edit/:id
  param: { module: settings, action: edit }

settings_do_delete_user:
  url:   /settings/user/delete/:id
  param: { module: settings, action: delete }

settings_contact_list:
  url:   /settings/contactList
  param: { module: settings, action: contactList }

settings_custom_fields:
  url:   /settings/customFields
  param: { module: settings, action: customFields }

settings_unsubscribe:
  url:   /settings/unsubscribe
  param: { module: settings, action: unsubscribe }

settings_change_list_limit:
  url:   /settings/contactListLimit
  param: { module: settings, action: changeContactListLimit }

# generic rules
# please, remove them by adding more specific rules
default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*
