<?php


/**
 * Skeleton subclass for representing a row from the 'campaign_link' table.
 *
 *
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * jeu. 03 mai 2012 11:26:45 CEST
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class CampaignLink extends BaseCampaignLink {
	public function getCollectorLink($position)
	{
		$key = sprintf('#EMAIL#-%d-%d', $this->getId(),$position);
		return CatalyzEmailing::getApplicationUrl().'/campaign/link/key/'.$key;
	}

	public function getTrackedUrl()
	{
		$url= $this->getUrl();

		$campaign = /*(Campaign)*/$this->getCampaign();

		if (!$campaign->getGoogleAnalyticsEnabled()) {
			return $url;
		}
		else{
			$params=array();
			foreach (array('utm_source'=>$campaign->getGoogleAnalyticsSource(),'utm_content'=>$campaign->getGoogleAnalyticsContent(),'utm_medium'=>$campaign->getGoogleAnalyticsMedium(),'utm_campaign'=>$campaign->getGoogleAnalyticsCampaignContent()) as $key=>$value){
				if (isset($value)) {
					$params[$key]=$value;
				}
			}

			if ($campaign->getGoogleAnalyticsCampaignType()==Campaign::ANALYTICS_CAMPAIGN_NAME) {
				$params['utm_campaign']=$campaign->getName();
			}elseif ($campaign->getGoogleAnalyticsCampaignType()==Campaign::ANALYTICS_CAMPAIGN_SUBJECT) {
				$params['utm_campaign']=$campaign->getSubject();
			}

			$term=$this->getGoogleAnalyticsTerm();
			if (isset($term)) {
				$params['utm_term']=$this->getGoogleAnalyticsTerm();
			}

			$sufix='?';
			if (preg_match('/\?/',$url)) {
				$sufix='&';
			}

			foreach ($params as $element=>$value){
				$url.=sprintf('%s%s=%s',$sufix,$element,urlencode($value));
				if ($sufix=='?') {
					$sufix='&';
				}
			}
		}
		return $url;
	}

	public function displayInGoogleAnalyticsTracker(){
		$uri = parse_url($this->getUrl(), PHP_URL_HOST);

		if (preg_match('#(w{3}\.?)(?<!www)(\w+-?)*\.([a-z]{2,4})#', $uri,$tok)) {
			foreach (sfConfig::get('app_divers_tracker_analytics_nofollow_domain',array()) as $domain){
				if (isset($tok[2]) && $tok[2] == $domain) {
					return FALSE;
				}
			}
		}

		return TRUE;
	}
} // CampaignLink
