<?php


/**
 * Skeleton subclass for performing query and update operations on the 'campaign_template' table.
 *
 *
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * jeu. 03 mai 2012 11:26:44 CEST
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class CampaignTemplatePeer extends BaseCampaignTemplatePeer {
	public static function retrieveBySlug($slug)
	{
		$criteria = new Criteria(CampaignTemplatePeer::DATABASE_NAME);
		$criteria->add(CampaignTemplatePeer::SLUG, $slug);

		$v = CampaignTemplatePeer::doSelectOne($criteria);

		return $v;
	}
} // CampaignTemplatePeer
